// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AnalyticsService_GetStats_FullMethodName      = "/analytics.v1.AnalyticsService/GetStats"
	AnalyticsService_GetTimeseries_FullMethodName = "/analytics.v1.AnalyticsService/GetTimeseries"
	AnalyticsService_GetPlatforms_FullMethodName  = "/analytics.v1.AnalyticsService/GetPlatforms"
	AnalyticsService_GetCountries_FullMethodName  = "/analytics.v1.AnalyticsService/GetCountries"
	AnalyticsService_GetReferrers_FullMethodName  = "/analytics.v1.AnalyticsService/GetReferrers"
)

// AnalyticsServiceClient is the client API for AnalyticsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AnalyticsService handles link analytics
type AnalyticsServiceClient interface {
	// Get overview statistics for a link
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// Get click data over time
	GetTimeseries(ctx context.Context, in *GetTimeseriesRequest, opts ...grpc.CallOption) (*GetTimeseriesResponse, error)
	// Get breakdown by platform
	GetPlatforms(ctx context.Context, in *GetPlatformsRequest, opts ...grpc.CallOption) (*GetPlatformsResponse, error)
	// Get breakdown by country
	GetCountries(ctx context.Context, in *GetCountriesRequest, opts ...grpc.CallOption) (*GetCountriesResponse, error)
	// Get top referrers
	GetReferrers(ctx context.Context, in *GetReferrersRequest, opts ...grpc.CallOption) (*GetReferrersResponse, error)
}

type analyticsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAnalyticsServiceClient(cc grpc.ClientConnInterface) AnalyticsServiceClient {
	return &analyticsServiceClient{cc}
}

func (c *analyticsServiceClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetTimeseries(ctx context.Context, in *GetTimeseriesRequest, opts ...grpc.CallOption) (*GetTimeseriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTimeseriesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetTimeseries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetPlatforms(ctx context.Context, in *GetPlatformsRequest, opts ...grpc.CallOption) (*GetPlatformsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformsResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetPlatforms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetCountries(ctx context.Context, in *GetCountriesRequest, opts ...grpc.CallOption) (*GetCountriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCountriesResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetCountries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *analyticsServiceClient) GetReferrers(ctx context.Context, in *GetReferrersRequest, opts ...grpc.CallOption) (*GetReferrersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetReferrersResponse)
	err := c.cc.Invoke(ctx, AnalyticsService_GetReferrers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AnalyticsServiceServer is the server API for AnalyticsService service.
// All implementations must embed UnimplementedAnalyticsServiceServer
// for forward compatibility.
//
// AnalyticsService handles link analytics
type AnalyticsServiceServer interface {
	// Get overview statistics for a link
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// Get click data over time
	GetTimeseries(context.Context, *GetTimeseriesRequest) (*GetTimeseriesResponse, error)
	// Get breakdown by platform
	GetPlatforms(context.Context, *GetPlatformsRequest) (*GetPlatformsResponse, error)
	// Get breakdown by country
	GetCountries(context.Context, *GetCountriesRequest) (*GetCountriesResponse, error)
	// Get top referrers
	GetReferrers(context.Context, *GetReferrersRequest) (*GetReferrersResponse, error)
	mustEmbedUnimplementedAnalyticsServiceServer()
}

// UnimplementedAnalyticsServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAnalyticsServiceServer struct{}

func (UnimplementedAnalyticsServiceServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetTimeseries(context.Context, *GetTimeseriesRequest) (*GetTimeseriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTimeseries not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetPlatforms(context.Context, *GetPlatformsRequest) (*GetPlatformsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPlatforms not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetCountries(context.Context, *GetCountriesRequest) (*GetCountriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCountries not implemented")
}
func (UnimplementedAnalyticsServiceServer) GetReferrers(context.Context, *GetReferrersRequest) (*GetReferrersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetReferrers not implemented")
}
func (UnimplementedAnalyticsServiceServer) mustEmbedUnimplementedAnalyticsServiceServer() {}
func (UnimplementedAnalyticsServiceServer) testEmbeddedByValue()                          {}

// UnsafeAnalyticsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AnalyticsServiceServer will
// result in compilation errors.
type UnsafeAnalyticsServiceServer interface {
	mustEmbedUnimplementedAnalyticsServiceServer()
}

func RegisterAnalyticsServiceServer(s grpc.ServiceRegistrar, srv AnalyticsServiceServer) {
	// If the following call panics, it indicates UnimplementedAnalyticsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AnalyticsService_ServiceDesc, srv)
}

func _AnalyticsService_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetTimeseries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTimeseriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetTimeseries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetTimeseries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetTimeseries(ctx, req.(*GetTimeseriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetPlatforms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetPlatforms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetPlatforms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetPlatforms(ctx, req.(*GetPlatformsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetCountries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCountriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetCountries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetCountries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetCountries(ctx, req.(*GetCountriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AnalyticsService_GetReferrers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReferrersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnalyticsServiceServer).GetReferrers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AnalyticsService_GetReferrers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnalyticsServiceServer).GetReferrers(ctx, req.(*GetReferrersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AnalyticsService_ServiceDesc is the grpc.ServiceDesc for AnalyticsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AnalyticsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "analytics.v1.AnalyticsService",
	HandlerType: (*AnalyticsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _AnalyticsService_GetStats_Handler,
		},
		{
			MethodName: "GetTimeseries",
			Handler:    _AnalyticsService_GetTimeseries_Handler,
		},
		{
			MethodName: "GetPlatforms",
			Handler:    _AnalyticsService_GetPlatforms_Handler,
		},
		{
			MethodName: "GetCountries",
			Handler:    _AnalyticsService_GetCountries_Handler,
		},
		{
			MethodName: "GetReferrers",
			Handler:    _AnalyticsService_GetReferrers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "analytics/v1/analytics.proto",
}
