// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: analytics/v1/analytics.proto

package analyticsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Get stats
type GetStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // 7d, 30d, 90d
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsRequest) Reset() {
	*x = GetStatsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsRequest) ProtoMessage() {}

func (x *GetStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsRequest.ProtoReflect.Descriptor instead.
func (*GetStatsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetStatsRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetStatsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TotalClicks   int64                  `protobuf:"varint,1,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks  int64                  `protobuf:"varint,2,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	IosClicks     int64                  `protobuf:"varint,3,opt,name=ios_clicks,json=iosClicks,proto3" json:"ios_clicks,omitempty"`
	AndroidClicks int64                  `protobuf:"varint,4,opt,name=android_clicks,json=androidClicks,proto3" json:"android_clicks,omitempty"`
	WebClicks     int64                  `protobuf:"varint,5,opt,name=web_clicks,json=webClicks,proto3" json:"web_clicks,omitempty"`
	OtherClicks   int64                  `protobuf:"varint,6,opt,name=other_clicks,json=otherClicks,proto3" json:"other_clicks,omitempty"`
	TopCountries  []*CountryStats        `protobuf:"bytes,7,rep,name=top_countries,json=topCountries,proto3" json:"top_countries,omitempty"`
	TopReferrers  []*ReferrerStats       `protobuf:"bytes,8,rep,name=top_referrers,json=topReferrers,proto3" json:"top_referrers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatsResponse) Reset() {
	*x = GetStatsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatsResponse) ProtoMessage() {}

func (x *GetStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatsResponse.ProtoReflect.Descriptor instead.
func (*GetStatsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *GetStatsResponse) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *GetStatsResponse) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *GetStatsResponse) GetIosClicks() int64 {
	if x != nil {
		return x.IosClicks
	}
	return 0
}

func (x *GetStatsResponse) GetAndroidClicks() int64 {
	if x != nil {
		return x.AndroidClicks
	}
	return 0
}

func (x *GetStatsResponse) GetWebClicks() int64 {
	if x != nil {
		return x.WebClicks
	}
	return 0
}

func (x *GetStatsResponse) GetOtherClicks() int64 {
	if x != nil {
		return x.OtherClicks
	}
	return 0
}

func (x *GetStatsResponse) GetTopCountries() []*CountryStats {
	if x != nil {
		return x.TopCountries
	}
	return nil
}

func (x *GetStatsResponse) GetTopReferrers() []*ReferrerStats {
	if x != nil {
		return x.TopReferrers
	}
	return nil
}

// Get timeseries
type GetTimeseriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // 7d, 30d, 90d
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeseriesRequest) Reset() {
	*x = GetTimeseriesRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeseriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeseriesRequest) ProtoMessage() {}

func (x *GetTimeseriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeseriesRequest.ProtoReflect.Descriptor instead.
func (*GetTimeseriesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetTimeseriesRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetTimeseriesRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetTimeseriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TimeseriesPoint     `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTimeseriesResponse) Reset() {
	*x = GetTimeseriesResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTimeseriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTimeseriesResponse) ProtoMessage() {}

func (x *GetTimeseriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTimeseriesResponse.ProtoReflect.Descriptor instead.
func (*GetTimeseriesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *GetTimeseriesResponse) GetPoints() []*TimeseriesPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type TimeseriesPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	UniqueClicks  int64                  `protobuf:"varint,3,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeseriesPoint) Reset() {
	*x = TimeseriesPoint{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeseriesPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeseriesPoint) ProtoMessage() {}

func (x *TimeseriesPoint) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeseriesPoint.ProtoReflect.Descriptor instead.
func (*TimeseriesPoint) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *TimeseriesPoint) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *TimeseriesPoint) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *TimeseriesPoint) GetUniqueClicks() int64 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

// Get platforms
type GetPlatformsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // 7d, 30d, 90d
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformsRequest) Reset() {
	*x = GetPlatformsRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformsRequest) ProtoMessage() {}

func (x *GetPlatformsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformsRequest.ProtoReflect.Descriptor instead.
func (*GetPlatformsRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *GetPlatformsRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetPlatformsRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type GetPlatformsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platforms     []*PlatformStats       `protobuf:"bytes,1,rep,name=platforms,proto3" json:"platforms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPlatformsResponse) Reset() {
	*x = GetPlatformsResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPlatformsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPlatformsResponse) ProtoMessage() {}

func (x *GetPlatformsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPlatformsResponse.ProtoReflect.Descriptor instead.
func (*GetPlatformsResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{6}
}

func (x *GetPlatformsResponse) GetPlatforms() []*PlatformStats {
	if x != nil {
		return x.Platforms
	}
	return nil
}

type PlatformStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlatformStats) Reset() {
	*x = PlatformStats{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlatformStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatformStats) ProtoMessage() {}

func (x *PlatformStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatformStats.ProtoReflect.Descriptor instead.
func (*PlatformStats) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{7}
}

func (x *PlatformStats) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *PlatformStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *PlatformStats) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Get countries
type GetCountriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // 7d, 30d, 90d
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`  // Max number of results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountriesRequest) Reset() {
	*x = GetCountriesRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountriesRequest) ProtoMessage() {}

func (x *GetCountriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountriesRequest.ProtoReflect.Descriptor instead.
func (*GetCountriesRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{8}
}

func (x *GetCountriesRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetCountriesRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetCountriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetCountriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Countries     []*CountryStats        `protobuf:"bytes,1,rep,name=countries,proto3" json:"countries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCountriesResponse) Reset() {
	*x = GetCountriesResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCountriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCountriesResponse) ProtoMessage() {}

func (x *GetCountriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCountriesResponse.ProtoReflect.Descriptor instead.
func (*GetCountriesResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{9}
}

func (x *GetCountriesResponse) GetCountries() []*CountryStats {
	if x != nil {
		return x.Countries
	}
	return nil
}

type CountryStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CountryCode   string                 `protobuf:"bytes,1,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	CountryName   string                 `protobuf:"bytes,2,opt,name=country_name,json=countryName,proto3" json:"country_name,omitempty"`
	Clicks        int64                  `protobuf:"varint,3,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float64                `protobuf:"fixed64,4,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountryStats) Reset() {
	*x = CountryStats{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountryStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountryStats) ProtoMessage() {}

func (x *CountryStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountryStats.ProtoReflect.Descriptor instead.
func (*CountryStats) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{10}
}

func (x *CountryStats) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

func (x *CountryStats) GetCountryName() string {
	if x != nil {
		return x.CountryName
	}
	return ""
}

func (x *CountryStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *CountryStats) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

// Get referrers
type GetReferrersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LinkId        string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // 7d, 30d, 90d
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`  // Max number of results
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferrersRequest) Reset() {
	*x = GetReferrersRequest{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferrersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferrersRequest) ProtoMessage() {}

func (x *GetReferrersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferrersRequest.ProtoReflect.Descriptor instead.
func (*GetReferrersRequest) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{11}
}

func (x *GetReferrersRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GetReferrersRequest) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

func (x *GetReferrersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetReferrersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrers     []*ReferrerStats       `protobuf:"bytes,1,rep,name=referrers,proto3" json:"referrers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReferrersResponse) Reset() {
	*x = GetReferrersResponse{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReferrersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReferrersResponse) ProtoMessage() {}

func (x *GetReferrersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReferrersResponse.ProtoReflect.Descriptor instead.
func (*GetReferrersResponse) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{12}
}

func (x *GetReferrersResponse) GetReferrers() []*ReferrerStats {
	if x != nil {
		return x.Referrers
	}
	return nil
}

type ReferrerStats struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Referrer      string                 `protobuf:"bytes,1,opt,name=referrer,proto3" json:"referrer,omitempty"`
	Clicks        int64                  `protobuf:"varint,2,opt,name=clicks,proto3" json:"clicks,omitempty"`
	Percentage    float64                `protobuf:"fixed64,3,opt,name=percentage,proto3" json:"percentage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferrerStats) Reset() {
	*x = ReferrerStats{}
	mi := &file_analytics_v1_analytics_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferrerStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferrerStats) ProtoMessage() {}

func (x *ReferrerStats) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_v1_analytics_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferrerStats.ProtoReflect.Descriptor instead.
func (*ReferrerStats) Descriptor() ([]byte, []int) {
	return file_analytics_v1_analytics_proto_rawDescGZIP(), []int{13}
}

func (x *ReferrerStats) GetReferrer() string {
	if x != nil {
		return x.Referrer
	}
	return ""
}

func (x *ReferrerStats) GetClicks() int64 {
	if x != nil {
		return x.Clicks
	}
	return 0
}

func (x *ReferrerStats) GetPercentage() float64 {
	if x != nil {
		return x.Percentage
	}
	return 0
}

var File_analytics_v1_analytics_proto protoreflect.FileDescriptor

const file_analytics_v1_analytics_proto_rawDesc = "" +
	"\n" +
	"\x1canalytics/v1/analytics.proto\x12\fanalytics.v1\"B\n" +
	"\x0fGetStatsRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"\xe5\x02\n" +
	"\x10GetStatsResponse\x12!\n" +
	"\ftotal_clicks\x18\x01 \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\x02 \x01(\x03R\funiqueClicks\x12\x1d\n" +
	"\n" +
	"ios_clicks\x18\x03 \x01(\x03R\tiosClicks\x12%\n" +
	"\x0eandroid_clicks\x18\x04 \x01(\x03R\randroidClicks\x12\x1d\n" +
	"\n" +
	"web_clicks\x18\x05 \x01(\x03R\twebClicks\x12!\n" +
	"\fother_clicks\x18\x06 \x01(\x03R\votherClicks\x12?\n" +
	"\rtop_countries\x18\a \x03(\v2\x1a.analytics.v1.CountryStatsR\ftopCountries\x12@\n" +
	"\rtop_referrers\x18\b \x03(\v2\x1b.analytics.v1.ReferrerStatsR\ftopReferrers\"G\n" +
	"\x14GetTimeseriesRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"N\n" +
	"\x15GetTimeseriesResponse\x125\n" +
	"\x06points\x18\x01 \x03(\v2\x1d.analytics.v1.TimeseriesPointR\x06points\"b\n" +
	"\x0fTimeseriesPoint\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12#\n" +
	"\runique_clicks\x18\x03 \x01(\x03R\funiqueClicks\"F\n" +
	"\x13GetPlatformsRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"Q\n" +
	"\x14GetPlatformsResponse\x129\n" +
	"\tplatforms\x18\x01 \x03(\v2\x1b.analytics.v1.PlatformStatsR\tplatforms\"c\n" +
	"\rPlatformStats\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage\"\\\n" +
	"\x13GetCountriesRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"P\n" +
	"\x14GetCountriesResponse\x128\n" +
	"\tcountries\x18\x01 \x03(\v2\x1a.analytics.v1.CountryStatsR\tcountries\"\x8c\x01\n" +
	"\fCountryStats\x12!\n" +
	"\fcountry_code\x18\x01 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x02 \x01(\tR\vcountryName\x12\x16\n" +
	"\x06clicks\x18\x03 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x04 \x01(\x01R\n" +
	"percentage\"\\\n" +
	"\x13GetReferrersRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"Q\n" +
	"\x14GetReferrersResponse\x129\n" +
	"\treferrers\x18\x01 \x03(\v2\x1b.analytics.v1.ReferrerStatsR\treferrers\"c\n" +
	"\rReferrerStats\x12\x1a\n" +
	"\breferrer\x18\x01 \x01(\tR\breferrer\x12\x16\n" +
	"\x06clicks\x18\x02 \x01(\x03R\x06clicks\x12\x1e\n" +
	"\n" +
	"percentage\x18\x03 \x01(\x01R\n" +
	"percentage2\xbc\x03\n" +
	"\x10AnalyticsService\x12I\n" +
	"\bGetStats\x12\x1d.analytics.v1.GetStatsRequest\x1a\x1e.analytics.v1.GetStatsResponse\x12X\n" +
	"\rGetTimeseries\x12\".analytics.v1.GetTimeseriesRequest\x1a#.analytics.v1.GetTimeseriesResponse\x12U\n" +
	"\fGetPlatforms\x12!.analytics.v1.GetPlatformsRequest\x1a\".analytics.v1.GetPlatformsResponse\x12U\n" +
	"\fGetCountries\x12!.analytics.v1.GetCountriesRequest\x1a\".analytics.v1.GetCountriesResponse\x12U\n" +
	"\fGetReferrers\x12!.analytics.v1.GetReferrersRequest\x1a\".analytics.v1.GetReferrersResponseB9Z7github.com/gosms-ge/go2-sdk/go/analytics/v1;analyticsv1b\x06proto3"

var (
	file_analytics_v1_analytics_proto_rawDescOnce sync.Once
	file_analytics_v1_analytics_proto_rawDescData []byte
)

func file_analytics_v1_analytics_proto_rawDescGZIP() []byte {
	file_analytics_v1_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_v1_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)))
	})
	return file_analytics_v1_analytics_proto_rawDescData
}

var file_analytics_v1_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_analytics_v1_analytics_proto_goTypes = []any{
	(*GetStatsRequest)(nil),       // 0: analytics.v1.GetStatsRequest
	(*GetStatsResponse)(nil),      // 1: analytics.v1.GetStatsResponse
	(*GetTimeseriesRequest)(nil),  // 2: analytics.v1.GetTimeseriesRequest
	(*GetTimeseriesResponse)(nil), // 3: analytics.v1.GetTimeseriesResponse
	(*TimeseriesPoint)(nil),       // 4: analytics.v1.TimeseriesPoint
	(*GetPlatformsRequest)(nil),   // 5: analytics.v1.GetPlatformsRequest
	(*GetPlatformsResponse)(nil),  // 6: analytics.v1.GetPlatformsResponse
	(*PlatformStats)(nil),         // 7: analytics.v1.PlatformStats
	(*GetCountriesRequest)(nil),   // 8: analytics.v1.GetCountriesRequest
	(*GetCountriesResponse)(nil),  // 9: analytics.v1.GetCountriesResponse
	(*CountryStats)(nil),          // 10: analytics.v1.CountryStats
	(*GetReferrersRequest)(nil),   // 11: analytics.v1.GetReferrersRequest
	(*GetReferrersResponse)(nil),  // 12: analytics.v1.GetReferrersResponse
	(*ReferrerStats)(nil),         // 13: analytics.v1.ReferrerStats
}
var file_analytics_v1_analytics_proto_depIdxs = []int32{
	10, // 0: analytics.v1.GetStatsResponse.top_countries:type_name -> analytics.v1.CountryStats
	13, // 1: analytics.v1.GetStatsResponse.top_referrers:type_name -> analytics.v1.ReferrerStats
	4,  // 2: analytics.v1.GetTimeseriesResponse.points:type_name -> analytics.v1.TimeseriesPoint
	7,  // 3: analytics.v1.GetPlatformsResponse.platforms:type_name -> analytics.v1.PlatformStats
	10, // 4: analytics.v1.GetCountriesResponse.countries:type_name -> analytics.v1.CountryStats
	13, // 5: analytics.v1.GetReferrersResponse.referrers:type_name -> analytics.v1.ReferrerStats
	0,  // 6: analytics.v1.AnalyticsService.GetStats:input_type -> analytics.v1.GetStatsRequest
	2,  // 7: analytics.v1.AnalyticsService.GetTimeseries:input_type -> analytics.v1.GetTimeseriesRequest
	5,  // 8: analytics.v1.AnalyticsService.GetPlatforms:input_type -> analytics.v1.GetPlatformsRequest
	8,  // 9: analytics.v1.AnalyticsService.GetCountries:input_type -> analytics.v1.GetCountriesRequest
	11, // 10: analytics.v1.AnalyticsService.GetReferrers:input_type -> analytics.v1.GetReferrersRequest
	1,  // 11: analytics.v1.AnalyticsService.GetStats:output_type -> analytics.v1.GetStatsResponse
	3,  // 12: analytics.v1.AnalyticsService.GetTimeseries:output_type -> analytics.v1.GetTimeseriesResponse
	6,  // 13: analytics.v1.AnalyticsService.GetPlatforms:output_type -> analytics.v1.GetPlatformsResponse
	9,  // 14: analytics.v1.AnalyticsService.GetCountries:output_type -> analytics.v1.GetCountriesResponse
	12, // 15: analytics.v1.AnalyticsService.GetReferrers:output_type -> analytics.v1.GetReferrersResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_analytics_v1_analytics_proto_init() }
func file_analytics_v1_analytics_proto_init() {
	if File_analytics_v1_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_v1_analytics_proto_rawDesc), len(file_analytics_v1_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_v1_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_v1_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_v1_analytics_proto_msgTypes,
	}.Build()
	File_analytics_v1_analytics_proto = out.File
	file_analytics_v1_analytics_proto_goTypes = nil
	file_analytics_v1_analytics_proto_depIdxs = nil
}
