// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: links/v1/links.proto

package linksv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Link represents a smart link
type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Slug          string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,4,opt,name=title,proto3" json:"title,omitempty"`
	IosUrl        string                 `protobuf:"bytes,5,opt,name=ios_url,json=iosUrl,proto3" json:"ios_url,omitempty"`
	AndroidUrl    string                 `protobuf:"bytes,6,opt,name=android_url,json=androidUrl,proto3" json:"android_url,omitempty"`
	WebUrl        string                 `protobuf:"bytes,7,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	FallbackUrl   string                 `protobuf:"bytes,8,opt,name=fallback_url,json=fallbackUrl,proto3" json:"fallback_url,omitempty"`
	HuaweiUrl     string                 `protobuf:"bytes,9,opt,name=huawei_url,json=huaweiUrl,proto3" json:"huawei_url,omitempty"`
	AmazonUrl     string                 `protobuf:"bytes,10,opt,name=amazon_url,json=amazonUrl,proto3" json:"amazon_url,omitempty"`
	WindowsUrl    string                 `protobuf:"bytes,11,opt,name=windows_url,json=windowsUrl,proto3" json:"windows_url,omitempty"`
	MacosUrl      string                 `protobuf:"bytes,12,opt,name=macos_url,json=macosUrl,proto3" json:"macos_url,omitempty"`
	AppName       string                 `protobuf:"bytes,13,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppIconUrl    string                 `protobuf:"bytes,14,opt,name=app_icon_url,json=appIconUrl,proto3" json:"app_icon_url,omitempty"`
	Description   string                 `protobuf:"bytes,15,opt,name=description,proto3" json:"description,omitempty"`
	IsActive      bool                   `protobuf:"varint,16,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	TotalClicks   int64                  `protobuf:"varint,17,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_links_v1_links_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Link) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Link) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Link) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Link) GetIosUrl() string {
	if x != nil {
		return x.IosUrl
	}
	return ""
}

func (x *Link) GetAndroidUrl() string {
	if x != nil {
		return x.AndroidUrl
	}
	return ""
}

func (x *Link) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

func (x *Link) GetFallbackUrl() string {
	if x != nil {
		return x.FallbackUrl
	}
	return ""
}

func (x *Link) GetHuaweiUrl() string {
	if x != nil {
		return x.HuaweiUrl
	}
	return ""
}

func (x *Link) GetAmazonUrl() string {
	if x != nil {
		return x.AmazonUrl
	}
	return ""
}

func (x *Link) GetWindowsUrl() string {
	if x != nil {
		return x.WindowsUrl
	}
	return ""
}

func (x *Link) GetMacosUrl() string {
	if x != nil {
		return x.MacosUrl
	}
	return ""
}

func (x *Link) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *Link) GetAppIconUrl() string {
	if x != nil {
		return x.AppIconUrl
	}
	return ""
}

func (x *Link) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Link) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Link) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *Link) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Link) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// List links
type ListLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,2,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksRequest) Reset() {
	*x = ListLinksRequest{}
	mi := &file_links_v1_links_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksRequest) ProtoMessage() {}

func (x *ListLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksRequest.ProtoReflect.Descriptor instead.
func (*ListLinksRequest) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{1}
}

func (x *ListLinksRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLinksRequest) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

type ListLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*Link                `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PerPage       int32                  `protobuf:"varint,4,opt,name=per_page,json=perPage,proto3" json:"per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLinksResponse) Reset() {
	*x = ListLinksResponse{}
	mi := &file_links_v1_links_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLinksResponse) ProtoMessage() {}

func (x *ListLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLinksResponse.ProtoReflect.Descriptor instead.
func (*ListLinksResponse) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{2}
}

func (x *ListLinksResponse) GetLinks() []*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListLinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListLinksResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListLinksResponse) GetPerPage() int32 {
	if x != nil {
		return x.PerPage
	}
	return 0
}

// Create link
type CreateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	IosUrl        string                 `protobuf:"bytes,3,opt,name=ios_url,json=iosUrl,proto3" json:"ios_url,omitempty"`
	AndroidUrl    string                 `protobuf:"bytes,4,opt,name=android_url,json=androidUrl,proto3" json:"android_url,omitempty"`
	WebUrl        string                 `protobuf:"bytes,5,opt,name=web_url,json=webUrl,proto3" json:"web_url,omitempty"`
	FallbackUrl   string                 `protobuf:"bytes,6,opt,name=fallback_url,json=fallbackUrl,proto3" json:"fallback_url,omitempty"`
	HuaweiUrl     string                 `protobuf:"bytes,7,opt,name=huawei_url,json=huaweiUrl,proto3" json:"huawei_url,omitempty"`
	AmazonUrl     string                 `protobuf:"bytes,8,opt,name=amazon_url,json=amazonUrl,proto3" json:"amazon_url,omitempty"`
	WindowsUrl    string                 `protobuf:"bytes,9,opt,name=windows_url,json=windowsUrl,proto3" json:"windows_url,omitempty"`
	MacosUrl      string                 `protobuf:"bytes,10,opt,name=macos_url,json=macosUrl,proto3" json:"macos_url,omitempty"`
	AppName       string                 `protobuf:"bytes,11,opt,name=app_name,json=appName,proto3" json:"app_name,omitempty"`
	AppIconUrl    string                 `protobuf:"bytes,12,opt,name=app_icon_url,json=appIconUrl,proto3" json:"app_icon_url,omitempty"`
	Description   string                 `protobuf:"bytes,13,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLinkRequest) Reset() {
	*x = CreateLinkRequest{}
	mi := &file_links_v1_links_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLinkRequest) ProtoMessage() {}

func (x *CreateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLinkRequest.ProtoReflect.Descriptor instead.
func (*CreateLinkRequest) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{3}
}

func (x *CreateLinkRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateLinkRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateLinkRequest) GetIosUrl() string {
	if x != nil {
		return x.IosUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetAndroidUrl() string {
	if x != nil {
		return x.AndroidUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetWebUrl() string {
	if x != nil {
		return x.WebUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetFallbackUrl() string {
	if x != nil {
		return x.FallbackUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetHuaweiUrl() string {
	if x != nil {
		return x.HuaweiUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetAmazonUrl() string {
	if x != nil {
		return x.AmazonUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetWindowsUrl() string {
	if x != nil {
		return x.WindowsUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetMacosUrl() string {
	if x != nil {
		return x.MacosUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *CreateLinkRequest) GetAppIconUrl() string {
	if x != nil {
		return x.AppIconUrl
	}
	return ""
}

func (x *CreateLinkRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Get link
type GetLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLinkRequest) Reset() {
	*x = GetLinkRequest{}
	mi := &file_links_v1_links_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLinkRequest) ProtoMessage() {}

func (x *GetLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLinkRequest.ProtoReflect.Descriptor instead.
func (*GetLinkRequest) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{4}
}

func (x *GetLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Update link
type UpdateLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Slug          *string                `protobuf:"bytes,2,opt,name=slug,proto3,oneof" json:"slug,omitempty"`
	Title         *string                `protobuf:"bytes,3,opt,name=title,proto3,oneof" json:"title,omitempty"`
	IosUrl        *string                `protobuf:"bytes,4,opt,name=ios_url,json=iosUrl,proto3,oneof" json:"ios_url,omitempty"`
	AndroidUrl    *string                `protobuf:"bytes,5,opt,name=android_url,json=androidUrl,proto3,oneof" json:"android_url,omitempty"`
	WebUrl        *string                `protobuf:"bytes,6,opt,name=web_url,json=webUrl,proto3,oneof" json:"web_url,omitempty"`
	FallbackUrl   *string                `protobuf:"bytes,7,opt,name=fallback_url,json=fallbackUrl,proto3,oneof" json:"fallback_url,omitempty"`
	IsActive      *bool                  `protobuf:"varint,8,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLinkRequest) Reset() {
	*x = UpdateLinkRequest{}
	mi := &file_links_v1_links_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLinkRequest) ProtoMessage() {}

func (x *UpdateLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLinkRequest.ProtoReflect.Descriptor instead.
func (*UpdateLinkRequest) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateLinkRequest) GetSlug() string {
	if x != nil && x.Slug != nil {
		return *x.Slug
	}
	return ""
}

func (x *UpdateLinkRequest) GetTitle() string {
	if x != nil && x.Title != nil {
		return *x.Title
	}
	return ""
}

func (x *UpdateLinkRequest) GetIosUrl() string {
	if x != nil && x.IosUrl != nil {
		return *x.IosUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetAndroidUrl() string {
	if x != nil && x.AndroidUrl != nil {
		return *x.AndroidUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetWebUrl() string {
	if x != nil && x.WebUrl != nil {
		return *x.WebUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetFallbackUrl() string {
	if x != nil && x.FallbackUrl != nil {
		return *x.FallbackUrl
	}
	return ""
}

func (x *UpdateLinkRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

// Delete link
type DeleteLinkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkRequest) Reset() {
	*x = DeleteLinkRequest{}
	mi := &file_links_v1_links_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkRequest) ProtoMessage() {}

func (x *DeleteLinkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkRequest.ProtoReflect.Descriptor instead.
func (*DeleteLinkRequest) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteLinkRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteLinkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLinkResponse) Reset() {
	*x = DeleteLinkResponse{}
	mi := &file_links_v1_links_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLinkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLinkResponse) ProtoMessage() {}

func (x *DeleteLinkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLinkResponse.ProtoReflect.Descriptor instead.
func (*DeleteLinkResponse) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteLinkResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteLinkResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Check slug
type CheckSlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSlugRequest) Reset() {
	*x = CheckSlugRequest{}
	mi := &file_links_v1_links_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSlugRequest) ProtoMessage() {}

func (x *CheckSlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSlugRequest.ProtoReflect.Descriptor instead.
func (*CheckSlugRequest) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{8}
}

func (x *CheckSlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type CheckSlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Available     bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckSlugResponse) Reset() {
	*x = CheckSlugResponse{}
	mi := &file_links_v1_links_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckSlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSlugResponse) ProtoMessage() {}

func (x *CheckSlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_links_v1_links_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSlugResponse.ProtoReflect.Descriptor instead.
func (*CheckSlugResponse) Descriptor() ([]byte, []int) {
	return file_links_v1_links_proto_rawDescGZIP(), []int{9}
}

func (x *CheckSlugResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CheckSlugResponse) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

var File_links_v1_links_proto protoreflect.FileDescriptor

const file_links_v1_links_proto_rawDesc = "" +
	"\n" +
	"\x14links/v1/links.proto\x12\blinks.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe0\x04\n" +
	"\x04Link\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x04 \x01(\tR\x05title\x12\x17\n" +
	"\aios_url\x18\x05 \x01(\tR\x06iosUrl\x12\x1f\n" +
	"\vandroid_url\x18\x06 \x01(\tR\n" +
	"androidUrl\x12\x17\n" +
	"\aweb_url\x18\a \x01(\tR\x06webUrl\x12!\n" +
	"\ffallback_url\x18\b \x01(\tR\vfallbackUrl\x12\x1d\n" +
	"\n" +
	"huawei_url\x18\t \x01(\tR\thuaweiUrl\x12\x1d\n" +
	"\n" +
	"amazon_url\x18\n" +
	" \x01(\tR\tamazonUrl\x12\x1f\n" +
	"\vwindows_url\x18\v \x01(\tR\n" +
	"windowsUrl\x12\x1b\n" +
	"\tmacos_url\x18\f \x01(\tR\bmacosUrl\x12\x19\n" +
	"\bapp_name\x18\r \x01(\tR\aappName\x12 \n" +
	"\fapp_icon_url\x18\x0e \x01(\tR\n" +
	"appIconUrl\x12 \n" +
	"\vdescription\x18\x0f \x01(\tR\vdescription\x12\x1b\n" +
	"\tis_active\x18\x10 \x01(\bR\bisActive\x12!\n" +
	"\ftotal_clicks\x18\x11 \x01(\x03R\vtotalClicks\x129\n" +
	"\n" +
	"created_at\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"A\n" +
	"\x10ListLinksRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x02 \x01(\x05R\aperPage\"~\n" +
	"\x11ListLinksResponse\x12$\n" +
	"\x05links\x18\x01 \x03(\v2\x0e.links.v1.LinkR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x19\n" +
	"\bper_page\x18\x04 \x01(\x05R\aperPage\"\x8e\x03\n" +
	"\x11CreateLinkRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x17\n" +
	"\aios_url\x18\x03 \x01(\tR\x06iosUrl\x12\x1f\n" +
	"\vandroid_url\x18\x04 \x01(\tR\n" +
	"androidUrl\x12\x17\n" +
	"\aweb_url\x18\x05 \x01(\tR\x06webUrl\x12!\n" +
	"\ffallback_url\x18\x06 \x01(\tR\vfallbackUrl\x12\x1d\n" +
	"\n" +
	"huawei_url\x18\a \x01(\tR\thuaweiUrl\x12\x1d\n" +
	"\n" +
	"amazon_url\x18\b \x01(\tR\tamazonUrl\x12\x1f\n" +
	"\vwindows_url\x18\t \x01(\tR\n" +
	"windowsUrl\x12\x1b\n" +
	"\tmacos_url\x18\n" +
	" \x01(\tR\bmacosUrl\x12\x19\n" +
	"\bapp_name\x18\v \x01(\tR\aappName\x12 \n" +
	"\fapp_icon_url\x18\f \x01(\tR\n" +
	"appIconUrl\x12 \n" +
	"\vdescription\x18\r \x01(\tR\vdescription\" \n" +
	"\x0eGetLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xdd\x02\n" +
	"\x11UpdateLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04slug\x18\x02 \x01(\tH\x00R\x04slug\x88\x01\x01\x12\x19\n" +
	"\x05title\x18\x03 \x01(\tH\x01R\x05title\x88\x01\x01\x12\x1c\n" +
	"\aios_url\x18\x04 \x01(\tH\x02R\x06iosUrl\x88\x01\x01\x12$\n" +
	"\vandroid_url\x18\x05 \x01(\tH\x03R\n" +
	"androidUrl\x88\x01\x01\x12\x1c\n" +
	"\aweb_url\x18\x06 \x01(\tH\x04R\x06webUrl\x88\x01\x01\x12&\n" +
	"\ffallback_url\x18\a \x01(\tH\x05R\vfallbackUrl\x88\x01\x01\x12 \n" +
	"\tis_active\x18\b \x01(\bH\x06R\bisActive\x88\x01\x01B\a\n" +
	"\x05_slugB\b\n" +
	"\x06_titleB\n" +
	"\n" +
	"\b_ios_urlB\x0e\n" +
	"\f_android_urlB\n" +
	"\n" +
	"\b_web_urlB\x0f\n" +
	"\r_fallback_urlB\f\n" +
	"\n" +
	"_is_active\"#\n" +
	"\x11DeleteLinkRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"H\n" +
	"\x12DeleteLinkResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"&\n" +
	"\x10CheckSlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"E\n" +
	"\x11CheckSlugResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug2\x8d\x03\n" +
	"\vLinkService\x12D\n" +
	"\tListLinks\x12\x1a.links.v1.ListLinksRequest\x1a\x1b.links.v1.ListLinksResponse\x129\n" +
	"\n" +
	"CreateLink\x12\x1b.links.v1.CreateLinkRequest\x1a\x0e.links.v1.Link\x123\n" +
	"\aGetLink\x12\x18.links.v1.GetLinkRequest\x1a\x0e.links.v1.Link\x129\n" +
	"\n" +
	"UpdateLink\x12\x1b.links.v1.UpdateLinkRequest\x1a\x0e.links.v1.Link\x12G\n" +
	"\n" +
	"DeleteLink\x12\x1b.links.v1.DeleteLinkRequest\x1a\x1c.links.v1.DeleteLinkResponse\x12D\n" +
	"\tCheckSlug\x12\x1a.links.v1.CheckSlugRequest\x1a\x1b.links.v1.CheckSlugResponseB1Z/github.com/gosms-ge/go2-sdk/go/links/v1;linksv1b\x06proto3"

var (
	file_links_v1_links_proto_rawDescOnce sync.Once
	file_links_v1_links_proto_rawDescData []byte
)

func file_links_v1_links_proto_rawDescGZIP() []byte {
	file_links_v1_links_proto_rawDescOnce.Do(func() {
		file_links_v1_links_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_links_v1_links_proto_rawDesc), len(file_links_v1_links_proto_rawDesc)))
	})
	return file_links_v1_links_proto_rawDescData
}

var file_links_v1_links_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_links_v1_links_proto_goTypes = []any{
	(*Link)(nil),                  // 0: links.v1.Link
	(*ListLinksRequest)(nil),      // 1: links.v1.ListLinksRequest
	(*ListLinksResponse)(nil),     // 2: links.v1.ListLinksResponse
	(*CreateLinkRequest)(nil),     // 3: links.v1.CreateLinkRequest
	(*GetLinkRequest)(nil),        // 4: links.v1.GetLinkRequest
	(*UpdateLinkRequest)(nil),     // 5: links.v1.UpdateLinkRequest
	(*DeleteLinkRequest)(nil),     // 6: links.v1.DeleteLinkRequest
	(*DeleteLinkResponse)(nil),    // 7: links.v1.DeleteLinkResponse
	(*CheckSlugRequest)(nil),      // 8: links.v1.CheckSlugRequest
	(*CheckSlugResponse)(nil),     // 9: links.v1.CheckSlugResponse
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_links_v1_links_proto_depIdxs = []int32{
	10, // 0: links.v1.Link.created_at:type_name -> google.protobuf.Timestamp
	10, // 1: links.v1.Link.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: links.v1.ListLinksResponse.links:type_name -> links.v1.Link
	1,  // 3: links.v1.LinkService.ListLinks:input_type -> links.v1.ListLinksRequest
	3,  // 4: links.v1.LinkService.CreateLink:input_type -> links.v1.CreateLinkRequest
	4,  // 5: links.v1.LinkService.GetLink:input_type -> links.v1.GetLinkRequest
	5,  // 6: links.v1.LinkService.UpdateLink:input_type -> links.v1.UpdateLinkRequest
	6,  // 7: links.v1.LinkService.DeleteLink:input_type -> links.v1.DeleteLinkRequest
	8,  // 8: links.v1.LinkService.CheckSlug:input_type -> links.v1.CheckSlugRequest
	2,  // 9: links.v1.LinkService.ListLinks:output_type -> links.v1.ListLinksResponse
	0,  // 10: links.v1.LinkService.CreateLink:output_type -> links.v1.Link
	0,  // 11: links.v1.LinkService.GetLink:output_type -> links.v1.Link
	0,  // 12: links.v1.LinkService.UpdateLink:output_type -> links.v1.Link
	7,  // 13: links.v1.LinkService.DeleteLink:output_type -> links.v1.DeleteLinkResponse
	9,  // 14: links.v1.LinkService.CheckSlug:output_type -> links.v1.CheckSlugResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_links_v1_links_proto_init() }
func file_links_v1_links_proto_init() {
	if File_links_v1_links_proto != nil {
		return
	}
	file_links_v1_links_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_links_v1_links_proto_rawDesc), len(file_links_v1_links_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_links_v1_links_proto_goTypes,
		DependencyIndexes: file_links_v1_links_proto_depIdxs,
		MessageInfos:      file_links_v1_links_proto_msgTypes,
	}.Build()
	File_links_v1_links_proto = out.File
	file_links_v1_links_proto_goTypes = nil
	file_links_v1_links_proto_depIdxs = nil
}
