// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: campaigns/v1/campaigns.proto

package campaignsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Campaign represents an SMS/Email marketing campaign
type Campaign struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name               string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	DestinationUrl     string                 `protobuf:"bytes,5,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	PassRecipientId    bool                   `protobuf:"varint,6,opt,name=pass_recipient_id,json=passRecipientId,proto3" json:"pass_recipient_id,omitempty"`
	RecipientParamName string                 `protobuf:"bytes,7,opt,name=recipient_param_name,json=recipientParamName,proto3" json:"recipient_param_name,omitempty"`
	TotalRecipients    int32                  `protobuf:"varint,8,opt,name=total_recipients,json=totalRecipients,proto3" json:"total_recipients,omitempty"`
	TotalClicks        int64                  `protobuf:"varint,9,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks       int32                  `protobuf:"varint,10,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	Status             string                 `protobuf:"bytes,11,opt,name=status,proto3" json:"status,omitempty"` // active, paused, completed, archived
	CreatedAt          string                 `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,13,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,14,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Campaign) Reset() {
	*x = Campaign{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Campaign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Campaign) ProtoMessage() {}

func (x *Campaign) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Campaign.ProtoReflect.Descriptor instead.
func (*Campaign) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{0}
}

func (x *Campaign) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Campaign) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Campaign) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Campaign) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Campaign) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *Campaign) GetPassRecipientId() bool {
	if x != nil {
		return x.PassRecipientId
	}
	return false
}

func (x *Campaign) GetRecipientParamName() string {
	if x != nil {
		return x.RecipientParamName
	}
	return ""
}

func (x *Campaign) GetTotalRecipients() int32 {
	if x != nil {
		return x.TotalRecipients
	}
	return 0
}

func (x *Campaign) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *Campaign) GetUniqueClicks() int32 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *Campaign) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Campaign) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Campaign) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Campaign) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// CampaignLink represents an individual trackable link for a recipient
type CampaignLink struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CampaignId         string                 `protobuf:"bytes,2,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Slug               string                 `protobuf:"bytes,3,opt,name=slug,proto3" json:"slug,omitempty"`
	RecipientId        string                 `protobuf:"bytes,4,opt,name=recipient_id,json=recipientId,proto3" json:"recipient_id,omitempty"`
	RecipientName      string                 `protobuf:"bytes,5,opt,name=recipient_name,json=recipientName,proto3" json:"recipient_name,omitempty"`
	RecipientMetadata  map[string]string      `protobuf:"bytes,6,rep,name=recipient_metadata,json=recipientMetadata,proto3" json:"recipient_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Clicked            bool                   `protobuf:"varint,7,opt,name=clicked,proto3" json:"clicked,omitempty"`
	FirstClickedAt     string                 `protobuf:"bytes,8,opt,name=first_clicked_at,json=firstClickedAt,proto3" json:"first_clicked_at,omitempty"`
	LastClickedAt      string                 `protobuf:"bytes,9,opt,name=last_clicked_at,json=lastClickedAt,proto3" json:"last_clicked_at,omitempty"`
	ClickCount         int32                  `protobuf:"varint,10,opt,name=click_count,json=clickCount,proto3" json:"click_count,omitempty"`
	FirstClickPlatform string                 `protobuf:"bytes,11,opt,name=first_click_platform,json=firstClickPlatform,proto3" json:"first_click_platform,omitempty"`
	FirstClickCountry  string                 `protobuf:"bytes,12,opt,name=first_click_country,json=firstClickCountry,proto3" json:"first_click_country,omitempty"`
	FirstClickCity     string                 `protobuf:"bytes,13,opt,name=first_click_city,json=firstClickCity,proto3" json:"first_click_city,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ShortUrl           string                 `protobuf:"bytes,15,opt,name=short_url,json=shortUrl,proto3" json:"short_url,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CampaignLink) Reset() {
	*x = CampaignLink{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignLink) ProtoMessage() {}

func (x *CampaignLink) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignLink.ProtoReflect.Descriptor instead.
func (*CampaignLink) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{1}
}

func (x *CampaignLink) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CampaignLink) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignLink) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CampaignLink) GetRecipientId() string {
	if x != nil {
		return x.RecipientId
	}
	return ""
}

func (x *CampaignLink) GetRecipientName() string {
	if x != nil {
		return x.RecipientName
	}
	return ""
}

func (x *CampaignLink) GetRecipientMetadata() map[string]string {
	if x != nil {
		return x.RecipientMetadata
	}
	return nil
}

func (x *CampaignLink) GetClicked() bool {
	if x != nil {
		return x.Clicked
	}
	return false
}

func (x *CampaignLink) GetFirstClickedAt() string {
	if x != nil {
		return x.FirstClickedAt
	}
	return ""
}

func (x *CampaignLink) GetLastClickedAt() string {
	if x != nil {
		return x.LastClickedAt
	}
	return ""
}

func (x *CampaignLink) GetClickCount() int32 {
	if x != nil {
		return x.ClickCount
	}
	return 0
}

func (x *CampaignLink) GetFirstClickPlatform() string {
	if x != nil {
		return x.FirstClickPlatform
	}
	return ""
}

func (x *CampaignLink) GetFirstClickCountry() string {
	if x != nil {
		return x.FirstClickCountry
	}
	return ""
}

func (x *CampaignLink) GetFirstClickCity() string {
	if x != nil {
		return x.FirstClickCity
	}
	return ""
}

func (x *CampaignLink) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *CampaignLink) GetShortUrl() string {
	if x != nil {
		return x.ShortUrl
	}
	return ""
}

// Recipient for bulk link generation
type Recipient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Recipient) Reset() {
	*x = Recipient{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Recipient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Recipient) ProtoMessage() {}

func (x *Recipient) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Recipient.ProtoReflect.Descriptor instead.
func (*Recipient) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{2}
}

func (x *Recipient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Recipient) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Recipient) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// List campaigns
type ListCampaignsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"` // filter by status
	Search        string                 `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"` // search by name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsRequest) Reset() {
	*x = ListCampaignsRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsRequest) ProtoMessage() {}

func (x *ListCampaignsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignsRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{3}
}

func (x *ListCampaignsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCampaignsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCampaignsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListCampaignsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListCampaignsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Campaigns     []*Campaign            `protobuf:"bytes,1,rep,name=campaigns,proto3" json:"campaigns,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignsResponse) Reset() {
	*x = ListCampaignsResponse{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignsResponse) ProtoMessage() {}

func (x *ListCampaignsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignsResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignsResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{4}
}

func (x *ListCampaignsResponse) GetCampaigns() []*Campaign {
	if x != nil {
		return x.Campaigns
	}
	return nil
}

func (x *ListCampaignsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Create campaign
type CreateCampaignRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	DestinationUrl     string                 `protobuf:"bytes,3,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	PassRecipientId    bool                   `protobuf:"varint,4,opt,name=pass_recipient_id,json=passRecipientId,proto3" json:"pass_recipient_id,omitempty"`
	RecipientParamName string                 `protobuf:"bytes,5,opt,name=recipient_param_name,json=recipientParamName,proto3" json:"recipient_param_name,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,6,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateCampaignRequest) Reset() {
	*x = CreateCampaignRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCampaignRequest) ProtoMessage() {}

func (x *CreateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCampaignRequest.ProtoReflect.Descriptor instead.
func (*CreateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCampaignRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *CreateCampaignRequest) GetPassRecipientId() bool {
	if x != nil {
		return x.PassRecipientId
	}
	return false
}

func (x *CreateCampaignRequest) GetRecipientParamName() string {
	if x != nil {
		return x.RecipientParamName
	}
	return ""
}

func (x *CreateCampaignRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// Get campaign
type GetCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignRequest) Reset() {
	*x = GetCampaignRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignRequest) ProtoMessage() {}

func (x *GetCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{6}
}

func (x *GetCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Update campaign
type UpdateCampaignRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description        string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	DestinationUrl     string                 `protobuf:"bytes,4,opt,name=destination_url,json=destinationUrl,proto3" json:"destination_url,omitempty"`
	PassRecipientId    bool                   `protobuf:"varint,5,opt,name=pass_recipient_id,json=passRecipientId,proto3" json:"pass_recipient_id,omitempty"`
	RecipientParamName string                 `protobuf:"bytes,6,opt,name=recipient_param_name,json=recipientParamName,proto3" json:"recipient_param_name,omitempty"`
	Status             string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	ExpiresAt          string                 `protobuf:"bytes,8,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateCampaignRequest) Reset() {
	*x = UpdateCampaignRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCampaignRequest) ProtoMessage() {}

func (x *UpdateCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCampaignRequest.ProtoReflect.Descriptor instead.
func (*UpdateCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateCampaignRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateCampaignRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCampaignRequest) GetDestinationUrl() string {
	if x != nil {
		return x.DestinationUrl
	}
	return ""
}

func (x *UpdateCampaignRequest) GetPassRecipientId() bool {
	if x != nil {
		return x.PassRecipientId
	}
	return false
}

func (x *UpdateCampaignRequest) GetRecipientParamName() string {
	if x != nil {
		return x.RecipientParamName
	}
	return ""
}

func (x *UpdateCampaignRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateCampaignRequest) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

// Delete campaign
type DeleteCampaignRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignRequest) Reset() {
	*x = DeleteCampaignRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignRequest) ProtoMessage() {}

func (x *DeleteCampaignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignRequest.ProtoReflect.Descriptor instead.
func (*DeleteCampaignRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCampaignRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteCampaignResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCampaignResponse) Reset() {
	*x = DeleteCampaignResponse{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCampaignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCampaignResponse) ProtoMessage() {}

func (x *DeleteCampaignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCampaignResponse.ProtoReflect.Descriptor instead.
func (*DeleteCampaignResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCampaignResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Generate links
type GenerateLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Recipients    []*Recipient           `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateLinksRequest) Reset() {
	*x = GenerateLinksRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLinksRequest) ProtoMessage() {}

func (x *GenerateLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLinksRequest.ProtoReflect.Descriptor instead.
func (*GenerateLinksRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{10}
}

func (x *GenerateLinksRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *GenerateLinksRequest) GetRecipients() []*Recipient {
	if x != nil {
		return x.Recipients
	}
	return nil
}

type GenerateLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	LinksCreated  int32                  `protobuf:"varint,2,opt,name=links_created,json=linksCreated,proto3" json:"links_created,omitempty"`
	SampleLinks   []*CampaignLink        `protobuf:"bytes,3,rep,name=sample_links,json=sampleLinks,proto3" json:"sample_links,omitempty"` // First 10 links as sample
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateLinksResponse) Reset() {
	*x = GenerateLinksResponse{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateLinksResponse) ProtoMessage() {}

func (x *GenerateLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateLinksResponse.ProtoReflect.Descriptor instead.
func (*GenerateLinksResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{11}
}

func (x *GenerateLinksResponse) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *GenerateLinksResponse) GetLinksCreated() int32 {
	if x != nil {
		return x.LinksCreated
	}
	return 0
}

func (x *GenerateLinksResponse) GetSampleLinks() []*CampaignLink {
	if x != nil {
		return x.SampleLinks
	}
	return nil
}

// List campaign links
type ListCampaignLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	ClickedOnly   bool                   `protobuf:"varint,4,opt,name=clicked_only,json=clickedOnly,proto3" json:"clicked_only,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"` // Search by recipient_id or recipient_name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignLinksRequest) Reset() {
	*x = ListCampaignLinksRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignLinksRequest) ProtoMessage() {}

func (x *ListCampaignLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignLinksRequest.ProtoReflect.Descriptor instead.
func (*ListCampaignLinksRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{12}
}

func (x *ListCampaignLinksRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ListCampaignLinksRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCampaignLinksRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *ListCampaignLinksRequest) GetClickedOnly() bool {
	if x != nil {
		return x.ClickedOnly
	}
	return false
}

func (x *ListCampaignLinksRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

type ListCampaignLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*CampaignLink        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCampaignLinksResponse) Reset() {
	*x = ListCampaignLinksResponse{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCampaignLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCampaignLinksResponse) ProtoMessage() {}

func (x *ListCampaignLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCampaignLinksResponse.ProtoReflect.Descriptor instead.
func (*ListCampaignLinksResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{13}
}

func (x *ListCampaignLinksResponse) GetLinks() []*CampaignLink {
	if x != nil {
		return x.Links
	}
	return nil
}

func (x *ListCampaignLinksResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Get campaign stats
type GetCampaignStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCampaignStatsRequest) Reset() {
	*x = GetCampaignStatsRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCampaignStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCampaignStatsRequest) ProtoMessage() {}

func (x *GetCampaignStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCampaignStatsRequest.ProtoReflect.Descriptor instead.
func (*GetCampaignStatsRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{14}
}

func (x *GetCampaignStatsRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

type CampaignStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	CampaignId       string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	TotalRecipients  int32                  `protobuf:"varint,2,opt,name=total_recipients,json=totalRecipients,proto3" json:"total_recipients,omitempty"`
	TotalClicks      int64                  `protobuf:"varint,3,opt,name=total_clicks,json=totalClicks,proto3" json:"total_clicks,omitempty"`
	UniqueClicks     int32                  `protobuf:"varint,4,opt,name=unique_clicks,json=uniqueClicks,proto3" json:"unique_clicks,omitempty"`
	ClickRate        float64                `protobuf:"fixed64,5,opt,name=click_rate,json=clickRate,proto3" json:"click_rate,omitempty"` // unique_clicks / total_recipients * 100
	ClicksByPlatform map[string]int64       `protobuf:"bytes,6,rep,name=clicks_by_platform,json=clicksByPlatform,proto3" json:"clicks_by_platform,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClicksByCountry  map[string]int64       `protobuf:"bytes,7,rep,name=clicks_by_country,json=clicksByCountry,proto3" json:"clicks_by_country,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ClicksByDay      map[string]int64       `protobuf:"bytes,8,rep,name=clicks_by_day,json=clicksByDay,proto3" json:"clicks_by_day,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CampaignStats) Reset() {
	*x = CampaignStats{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CampaignStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CampaignStats) ProtoMessage() {}

func (x *CampaignStats) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CampaignStats.ProtoReflect.Descriptor instead.
func (*CampaignStats) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{15}
}

func (x *CampaignStats) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *CampaignStats) GetTotalRecipients() int32 {
	if x != nil {
		return x.TotalRecipients
	}
	return 0
}

func (x *CampaignStats) GetTotalClicks() int64 {
	if x != nil {
		return x.TotalClicks
	}
	return 0
}

func (x *CampaignStats) GetUniqueClicks() int32 {
	if x != nil {
		return x.UniqueClicks
	}
	return 0
}

func (x *CampaignStats) GetClickRate() float64 {
	if x != nil {
		return x.ClickRate
	}
	return 0
}

func (x *CampaignStats) GetClicksByPlatform() map[string]int64 {
	if x != nil {
		return x.ClicksByPlatform
	}
	return nil
}

func (x *CampaignStats) GetClicksByCountry() map[string]int64 {
	if x != nil {
		return x.ClicksByCountry
	}
	return nil
}

func (x *CampaignStats) GetClicksByDay() map[string]int64 {
	if x != nil {
		return x.ClicksByDay
	}
	return nil
}

// Export links
type ExportLinksRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CampaignId    string                 `protobuf:"bytes,1,opt,name=campaign_id,json=campaignId,proto3" json:"campaign_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // csv or json
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportLinksRequest) Reset() {
	*x = ExportLinksRequest{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportLinksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportLinksRequest) ProtoMessage() {}

func (x *ExportLinksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportLinksRequest.ProtoReflect.Descriptor instead.
func (*ExportLinksRequest) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{16}
}

func (x *ExportLinksRequest) GetCampaignId() string {
	if x != nil {
		return x.CampaignId
	}
	return ""
}

func (x *ExportLinksRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type ExportLinksResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         []*CampaignLink        `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportLinksResponse) Reset() {
	*x = ExportLinksResponse{}
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportLinksResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportLinksResponse) ProtoMessage() {}

func (x *ExportLinksResponse) ProtoReflect() protoreflect.Message {
	mi := &file_campaigns_v1_campaigns_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportLinksResponse.ProtoReflect.Descriptor instead.
func (*ExportLinksResponse) Descriptor() ([]byte, []int) {
	return file_campaigns_v1_campaigns_proto_rawDescGZIP(), []int{17}
}

func (x *ExportLinksResponse) GetLinks() []*CampaignLink {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_campaigns_v1_campaigns_proto protoreflect.FileDescriptor

const file_campaigns_v1_campaigns_proto_rawDesc = "" +
	"\n" +
	"\x1ccampaigns/v1/campaigns.proto\x12\fcampaigns.v1\"\xd8\x03\n" +
	"\bCampaign\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0fdestination_url\x18\x05 \x01(\tR\x0edestinationUrl\x12*\n" +
	"\x11pass_recipient_id\x18\x06 \x01(\bR\x0fpassRecipientId\x120\n" +
	"\x14recipient_param_name\x18\a \x01(\tR\x12recipientParamName\x12)\n" +
	"\x10total_recipients\x18\b \x01(\x05R\x0ftotalRecipients\x12!\n" +
	"\ftotal_clicks\x18\t \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\n" +
	" \x01(\x05R\funiqueClicks\x12\x16\n" +
	"\x06status\x18\v \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\f \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\r \x01(\tR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x0e \x01(\tR\texpiresAt\"\x9a\x05\n" +
	"\fCampaignLink\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vcampaign_id\x18\x02 \x01(\tR\n" +
	"campaignId\x12\x12\n" +
	"\x04slug\x18\x03 \x01(\tR\x04slug\x12!\n" +
	"\frecipient_id\x18\x04 \x01(\tR\vrecipientId\x12%\n" +
	"\x0erecipient_name\x18\x05 \x01(\tR\rrecipientName\x12`\n" +
	"\x12recipient_metadata\x18\x06 \x03(\v21.campaigns.v1.CampaignLink.RecipientMetadataEntryR\x11recipientMetadata\x12\x18\n" +
	"\aclicked\x18\a \x01(\bR\aclicked\x12(\n" +
	"\x10first_clicked_at\x18\b \x01(\tR\x0efirstClickedAt\x12&\n" +
	"\x0flast_clicked_at\x18\t \x01(\tR\rlastClickedAt\x12\x1f\n" +
	"\vclick_count\x18\n" +
	" \x01(\x05R\n" +
	"clickCount\x120\n" +
	"\x14first_click_platform\x18\v \x01(\tR\x12firstClickPlatform\x12.\n" +
	"\x13first_click_country\x18\f \x01(\tR\x11firstClickCountry\x12(\n" +
	"\x10first_click_city\x18\r \x01(\tR\x0efirstClickCity\x12\x1d\n" +
	"\n" +
	"created_at\x18\x0e \x01(\tR\tcreatedAt\x12\x1b\n" +
	"\tshort_url\x18\x0f \x01(\tR\bshortUrl\x1aD\n" +
	"\x16RecipientMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\tRecipient\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12A\n" +
	"\bmetadata\x18\x03 \x03(\v2%.campaigns.v1.Recipient.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"t\n" +
	"\x14ListCampaignsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x05R\x06offset\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x16\n" +
	"\x06search\x18\x04 \x01(\tR\x06search\"c\n" +
	"\x15ListCampaignsResponse\x124\n" +
	"\tcampaigns\x18\x01 \x03(\v2\x16.campaigns.v1.CampaignR\tcampaigns\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xf3\x01\n" +
	"\x15CreateCampaignRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12'\n" +
	"\x0fdestination_url\x18\x03 \x01(\tR\x0edestinationUrl\x12*\n" +
	"\x11pass_recipient_id\x18\x04 \x01(\bR\x0fpassRecipientId\x120\n" +
	"\x14recipient_param_name\x18\x05 \x01(\tR\x12recipientParamName\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x06 \x01(\tR\texpiresAt\"$\n" +
	"\x12GetCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x9b\x02\n" +
	"\x15UpdateCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\x0fdestination_url\x18\x04 \x01(\tR\x0edestinationUrl\x12*\n" +
	"\x11pass_recipient_id\x18\x05 \x01(\bR\x0fpassRecipientId\x120\n" +
	"\x14recipient_param_name\x18\x06 \x01(\tR\x12recipientParamName\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"expires_at\x18\b \x01(\tR\texpiresAt\"'\n" +
	"\x15DeleteCampaignRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteCampaignResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"p\n" +
	"\x14GenerateLinksRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x127\n" +
	"\n" +
	"recipients\x18\x02 \x03(\v2\x17.campaigns.v1.RecipientR\n" +
	"recipients\"\x9c\x01\n" +
	"\x15GenerateLinksResponse\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12#\n" +
	"\rlinks_created\x18\x02 \x01(\x05R\flinksCreated\x12=\n" +
	"\fsample_links\x18\x03 \x03(\v2\x1a.campaigns.v1.CampaignLinkR\vsampleLinks\"\xa4\x01\n" +
	"\x18ListCampaignLinksRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\x12!\n" +
	"\fclicked_only\x18\x04 \x01(\bR\vclickedOnly\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\"c\n" +
	"\x19ListCampaignLinksResponse\x120\n" +
	"\x05links\x18\x01 \x03(\v2\x1a.campaigns.v1.CampaignLinkR\x05links\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\":\n" +
	"\x17GetCampaignStatsRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\"\x9c\x05\n" +
	"\rCampaignStats\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12)\n" +
	"\x10total_recipients\x18\x02 \x01(\x05R\x0ftotalRecipients\x12!\n" +
	"\ftotal_clicks\x18\x03 \x01(\x03R\vtotalClicks\x12#\n" +
	"\runique_clicks\x18\x04 \x01(\x05R\funiqueClicks\x12\x1d\n" +
	"\n" +
	"click_rate\x18\x05 \x01(\x01R\tclickRate\x12_\n" +
	"\x12clicks_by_platform\x18\x06 \x03(\v21.campaigns.v1.CampaignStats.ClicksByPlatformEntryR\x10clicksByPlatform\x12\\\n" +
	"\x11clicks_by_country\x18\a \x03(\v20.campaigns.v1.CampaignStats.ClicksByCountryEntryR\x0fclicksByCountry\x12P\n" +
	"\rclicks_by_day\x18\b \x03(\v2,.campaigns.v1.CampaignStats.ClicksByDayEntryR\vclicksByDay\x1aC\n" +
	"\x15ClicksByPlatformEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1aB\n" +
	"\x14ClicksByCountryEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a>\n" +
	"\x10ClicksByDayEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\"M\n" +
	"\x12ExportLinksRequest\x12\x1f\n" +
	"\vcampaign_id\x18\x01 \x01(\tR\n" +
	"campaignId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"G\n" +
	"\x13ExportLinksResponse\x120\n" +
	"\x05links\x18\x01 \x03(\v2\x1a.campaigns.v1.CampaignLinkR\x05links2\x9b\x06\n" +
	"\x0fCampaignService\x12X\n" +
	"\rListCampaigns\x12\".campaigns.v1.ListCampaignsRequest\x1a#.campaigns.v1.ListCampaignsResponse\x12M\n" +
	"\x0eCreateCampaign\x12#.campaigns.v1.CreateCampaignRequest\x1a\x16.campaigns.v1.Campaign\x12G\n" +
	"\vGetCampaign\x12 .campaigns.v1.GetCampaignRequest\x1a\x16.campaigns.v1.Campaign\x12M\n" +
	"\x0eUpdateCampaign\x12#.campaigns.v1.UpdateCampaignRequest\x1a\x16.campaigns.v1.Campaign\x12[\n" +
	"\x0eDeleteCampaign\x12#.campaigns.v1.DeleteCampaignRequest\x1a$.campaigns.v1.DeleteCampaignResponse\x12X\n" +
	"\rGenerateLinks\x12\".campaigns.v1.GenerateLinksRequest\x1a#.campaigns.v1.GenerateLinksResponse\x12d\n" +
	"\x11ListCampaignLinks\x12&.campaigns.v1.ListCampaignLinksRequest\x1a'.campaigns.v1.ListCampaignLinksResponse\x12V\n" +
	"\x10GetCampaignStats\x12%.campaigns.v1.GetCampaignStatsRequest\x1a\x1b.campaigns.v1.CampaignStats\x12R\n" +
	"\vExportLinks\x12 .campaigns.v1.ExportLinksRequest\x1a!.campaigns.v1.ExportLinksResponseB9Z7github.com/gosms-ge/go2-sdk/go/campaigns/v1;campaignsv1b\x06proto3"

var (
	file_campaigns_v1_campaigns_proto_rawDescOnce sync.Once
	file_campaigns_v1_campaigns_proto_rawDescData []byte
)

func file_campaigns_v1_campaigns_proto_rawDescGZIP() []byte {
	file_campaigns_v1_campaigns_proto_rawDescOnce.Do(func() {
		file_campaigns_v1_campaigns_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_campaigns_v1_campaigns_proto_rawDesc), len(file_campaigns_v1_campaigns_proto_rawDesc)))
	})
	return file_campaigns_v1_campaigns_proto_rawDescData
}

var file_campaigns_v1_campaigns_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_campaigns_v1_campaigns_proto_goTypes = []any{
	(*Campaign)(nil),                  // 0: campaigns.v1.Campaign
	(*CampaignLink)(nil),              // 1: campaigns.v1.CampaignLink
	(*Recipient)(nil),                 // 2: campaigns.v1.Recipient
	(*ListCampaignsRequest)(nil),      // 3: campaigns.v1.ListCampaignsRequest
	(*ListCampaignsResponse)(nil),     // 4: campaigns.v1.ListCampaignsResponse
	(*CreateCampaignRequest)(nil),     // 5: campaigns.v1.CreateCampaignRequest
	(*GetCampaignRequest)(nil),        // 6: campaigns.v1.GetCampaignRequest
	(*UpdateCampaignRequest)(nil),     // 7: campaigns.v1.UpdateCampaignRequest
	(*DeleteCampaignRequest)(nil),     // 8: campaigns.v1.DeleteCampaignRequest
	(*DeleteCampaignResponse)(nil),    // 9: campaigns.v1.DeleteCampaignResponse
	(*GenerateLinksRequest)(nil),      // 10: campaigns.v1.GenerateLinksRequest
	(*GenerateLinksResponse)(nil),     // 11: campaigns.v1.GenerateLinksResponse
	(*ListCampaignLinksRequest)(nil),  // 12: campaigns.v1.ListCampaignLinksRequest
	(*ListCampaignLinksResponse)(nil), // 13: campaigns.v1.ListCampaignLinksResponse
	(*GetCampaignStatsRequest)(nil),   // 14: campaigns.v1.GetCampaignStatsRequest
	(*CampaignStats)(nil),             // 15: campaigns.v1.CampaignStats
	(*ExportLinksRequest)(nil),        // 16: campaigns.v1.ExportLinksRequest
	(*ExportLinksResponse)(nil),       // 17: campaigns.v1.ExportLinksResponse
	nil,                               // 18: campaigns.v1.CampaignLink.RecipientMetadataEntry
	nil,                               // 19: campaigns.v1.Recipient.MetadataEntry
	nil,                               // 20: campaigns.v1.CampaignStats.ClicksByPlatformEntry
	nil,                               // 21: campaigns.v1.CampaignStats.ClicksByCountryEntry
	nil,                               // 22: campaigns.v1.CampaignStats.ClicksByDayEntry
}
var file_campaigns_v1_campaigns_proto_depIdxs = []int32{
	18, // 0: campaigns.v1.CampaignLink.recipient_metadata:type_name -> campaigns.v1.CampaignLink.RecipientMetadataEntry
	19, // 1: campaigns.v1.Recipient.metadata:type_name -> campaigns.v1.Recipient.MetadataEntry
	0,  // 2: campaigns.v1.ListCampaignsResponse.campaigns:type_name -> campaigns.v1.Campaign
	2,  // 3: campaigns.v1.GenerateLinksRequest.recipients:type_name -> campaigns.v1.Recipient
	1,  // 4: campaigns.v1.GenerateLinksResponse.sample_links:type_name -> campaigns.v1.CampaignLink
	1,  // 5: campaigns.v1.ListCampaignLinksResponse.links:type_name -> campaigns.v1.CampaignLink
	20, // 6: campaigns.v1.CampaignStats.clicks_by_platform:type_name -> campaigns.v1.CampaignStats.ClicksByPlatformEntry
	21, // 7: campaigns.v1.CampaignStats.clicks_by_country:type_name -> campaigns.v1.CampaignStats.ClicksByCountryEntry
	22, // 8: campaigns.v1.CampaignStats.clicks_by_day:type_name -> campaigns.v1.CampaignStats.ClicksByDayEntry
	1,  // 9: campaigns.v1.ExportLinksResponse.links:type_name -> campaigns.v1.CampaignLink
	3,  // 10: campaigns.v1.CampaignService.ListCampaigns:input_type -> campaigns.v1.ListCampaignsRequest
	5,  // 11: campaigns.v1.CampaignService.CreateCampaign:input_type -> campaigns.v1.CreateCampaignRequest
	6,  // 12: campaigns.v1.CampaignService.GetCampaign:input_type -> campaigns.v1.GetCampaignRequest
	7,  // 13: campaigns.v1.CampaignService.UpdateCampaign:input_type -> campaigns.v1.UpdateCampaignRequest
	8,  // 14: campaigns.v1.CampaignService.DeleteCampaign:input_type -> campaigns.v1.DeleteCampaignRequest
	10, // 15: campaigns.v1.CampaignService.GenerateLinks:input_type -> campaigns.v1.GenerateLinksRequest
	12, // 16: campaigns.v1.CampaignService.ListCampaignLinks:input_type -> campaigns.v1.ListCampaignLinksRequest
	14, // 17: campaigns.v1.CampaignService.GetCampaignStats:input_type -> campaigns.v1.GetCampaignStatsRequest
	16, // 18: campaigns.v1.CampaignService.ExportLinks:input_type -> campaigns.v1.ExportLinksRequest
	4,  // 19: campaigns.v1.CampaignService.ListCampaigns:output_type -> campaigns.v1.ListCampaignsResponse
	0,  // 20: campaigns.v1.CampaignService.CreateCampaign:output_type -> campaigns.v1.Campaign
	0,  // 21: campaigns.v1.CampaignService.GetCampaign:output_type -> campaigns.v1.Campaign
	0,  // 22: campaigns.v1.CampaignService.UpdateCampaign:output_type -> campaigns.v1.Campaign
	9,  // 23: campaigns.v1.CampaignService.DeleteCampaign:output_type -> campaigns.v1.DeleteCampaignResponse
	11, // 24: campaigns.v1.CampaignService.GenerateLinks:output_type -> campaigns.v1.GenerateLinksResponse
	13, // 25: campaigns.v1.CampaignService.ListCampaignLinks:output_type -> campaigns.v1.ListCampaignLinksResponse
	15, // 26: campaigns.v1.CampaignService.GetCampaignStats:output_type -> campaigns.v1.CampaignStats
	17, // 27: campaigns.v1.CampaignService.ExportLinks:output_type -> campaigns.v1.ExportLinksResponse
	19, // [19:28] is the sub-list for method output_type
	10, // [10:19] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_campaigns_v1_campaigns_proto_init() }
func file_campaigns_v1_campaigns_proto_init() {
	if File_campaigns_v1_campaigns_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_campaigns_v1_campaigns_proto_rawDesc), len(file_campaigns_v1_campaigns_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_campaigns_v1_campaigns_proto_goTypes,
		DependencyIndexes: file_campaigns_v1_campaigns_proto_depIdxs,
		MessageInfos:      file_campaigns_v1_campaigns_proto_msgTypes,
	}.Build()
	File_campaigns_v1_campaigns_proto = out.File
	file_campaigns_v1_campaigns_proto_goTypes = nil
	file_campaigns_v1_campaigns_proto_depIdxs = nil
}
