// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: integrations/v1/integrations.proto

package integrationsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Integration types
type IntegrationType int32

const (
	IntegrationType_INTEGRATION_TYPE_UNSPECIFIED IntegrationType = 0
	IntegrationType_INTEGRATION_TYPE_SLACK       IntegrationType = 1
	IntegrationType_INTEGRATION_TYPE_DISCORD     IntegrationType = 2
	IntegrationType_INTEGRATION_TYPE_TELEGRAM    IntegrationType = 3
	IntegrationType_INTEGRATION_TYPE_SEGMENT     IntegrationType = 4
	IntegrationType_INTEGRATION_TYPE_ZAPIER      IntegrationType = 5
)

// Enum value maps for IntegrationType.
var (
	IntegrationType_name = map[int32]string{
		0: "INTEGRATION_TYPE_UNSPECIFIED",
		1: "INTEGRATION_TYPE_SLACK",
		2: "INTEGRATION_TYPE_DISCORD",
		3: "INTEGRATION_TYPE_TELEGRAM",
		4: "INTEGRATION_TYPE_SEGMENT",
		5: "INTEGRATION_TYPE_ZAPIER",
	}
	IntegrationType_value = map[string]int32{
		"INTEGRATION_TYPE_UNSPECIFIED": 0,
		"INTEGRATION_TYPE_SLACK":       1,
		"INTEGRATION_TYPE_DISCORD":     2,
		"INTEGRATION_TYPE_TELEGRAM":    3,
		"INTEGRATION_TYPE_SEGMENT":     4,
		"INTEGRATION_TYPE_ZAPIER":      5,
	}
)

func (x IntegrationType) Enum() *IntegrationType {
	p := new(IntegrationType)
	*p = x
	return p
}

func (x IntegrationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IntegrationType) Descriptor() protoreflect.EnumDescriptor {
	return file_integrations_v1_integrations_proto_enumTypes[0].Descriptor()
}

func (IntegrationType) Type() protoreflect.EnumType {
	return &file_integrations_v1_integrations_proto_enumTypes[0]
}

func (x IntegrationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IntegrationType.Descriptor instead.
func (IntegrationType) EnumDescriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{0}
}

// Integration represents a third-party integration
type Integration struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type            IntegrationType        `protobuf:"varint,3,opt,name=type,proto3,enum=integrations.v1.IntegrationType" json:"type,omitempty"`
	Name            string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Config          *IntegrationConfig     `protobuf:"bytes,5,opt,name=config,proto3" json:"config,omitempty"`
	Events          []string               `protobuf:"bytes,6,rep,name=events,proto3" json:"events,omitempty"`
	IsActive        bool                   `protobuf:"varint,7,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	LastTriggeredAt *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=last_triggered_at,json=lastTriggeredAt,proto3,oneof" json:"last_triggered_at,omitempty"`
	TriggerCount    int32                  `protobuf:"varint,9,opt,name=trigger_count,json=triggerCount,proto3" json:"trigger_count,omitempty"`
	CreatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Integration) Reset() {
	*x = Integration{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Integration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Integration) ProtoMessage() {}

func (x *Integration) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Integration.ProtoReflect.Descriptor instead.
func (*Integration) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{0}
}

func (x *Integration) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Integration) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Integration) GetType() IntegrationType {
	if x != nil {
		return x.Type
	}
	return IntegrationType_INTEGRATION_TYPE_UNSPECIFIED
}

func (x *Integration) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Integration) GetConfig() *IntegrationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Integration) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *Integration) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Integration) GetLastTriggeredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastTriggeredAt
	}
	return nil
}

func (x *Integration) GetTriggerCount() int32 {
	if x != nil {
		return x.TriggerCount
	}
	return 0
}

func (x *Integration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Integration) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// IntegrationConfig holds type-specific configuration
type IntegrationConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Slack/Discord/Zapier
	WebhookUrl string `protobuf:"bytes,1,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	Channel    string `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// Telegram
	BotToken string `protobuf:"bytes,3,opt,name=bot_token,json=botToken,proto3" json:"bot_token,omitempty"`
	ChatId   string `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	// Segment
	WriteKey      string `protobuf:"bytes,5,opt,name=write_key,json=writeKey,proto3" json:"write_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationConfig) Reset() {
	*x = IntegrationConfig{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationConfig) ProtoMessage() {}

func (x *IntegrationConfig) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationConfig.ProtoReflect.Descriptor instead.
func (*IntegrationConfig) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{1}
}

func (x *IntegrationConfig) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *IntegrationConfig) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

func (x *IntegrationConfig) GetBotToken() string {
	if x != nil {
		return x.BotToken
	}
	return ""
}

func (x *IntegrationConfig) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *IntegrationConfig) GetWriteKey() string {
	if x != nil {
		return x.WriteKey
	}
	return ""
}

// List integrations
type ListIntegrationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntegrationsRequest) Reset() {
	*x = ListIntegrationsRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntegrationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntegrationsRequest) ProtoMessage() {}

func (x *ListIntegrationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntegrationsRequest.ProtoReflect.Descriptor instead.
func (*ListIntegrationsRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{2}
}

type ListIntegrationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Integrations  []*Integration         `protobuf:"bytes,1,rep,name=integrations,proto3" json:"integrations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListIntegrationsResponse) Reset() {
	*x = ListIntegrationsResponse{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIntegrationsResponse) ProtoMessage() {}

func (x *ListIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*ListIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{3}
}

func (x *ListIntegrationsResponse) GetIntegrations() []*Integration {
	if x != nil {
		return x.Integrations
	}
	return nil
}

// Create integration
type CreateIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IntegrationType        `protobuf:"varint,1,opt,name=type,proto3,enum=integrations.v1.IntegrationType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *IntegrationConfig     `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Events        []string               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateIntegrationRequest) Reset() {
	*x = CreateIntegrationRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIntegrationRequest) ProtoMessage() {}

func (x *CreateIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIntegrationRequest.ProtoReflect.Descriptor instead.
func (*CreateIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{4}
}

func (x *CreateIntegrationRequest) GetType() IntegrationType {
	if x != nil {
		return x.Type
	}
	return IntegrationType_INTEGRATION_TYPE_UNSPECIFIED
}

func (x *CreateIntegrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateIntegrationRequest) GetConfig() *IntegrationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *CreateIntegrationRequest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

// Get integration
type GetIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationRequest) Reset() {
	*x = GetIntegrationRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationRequest) ProtoMessage() {}

func (x *GetIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{5}
}

func (x *GetIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Update integration
type UpdateIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Config        *IntegrationConfig     `protobuf:"bytes,3,opt,name=config,proto3,oneof" json:"config,omitempty"`
	Events        []string               `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	IsActive      *bool                  `protobuf:"varint,5,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateIntegrationRequest) Reset() {
	*x = UpdateIntegrationRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIntegrationRequest) ProtoMessage() {}

func (x *UpdateIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIntegrationRequest.ProtoReflect.Descriptor instead.
func (*UpdateIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateIntegrationRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateIntegrationRequest) GetConfig() *IntegrationConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateIntegrationRequest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *UpdateIntegrationRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

// Delete integration
type DeleteIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIntegrationRequest) Reset() {
	*x = DeleteIntegrationRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntegrationRequest) ProtoMessage() {}

func (x *DeleteIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntegrationRequest.ProtoReflect.Descriptor instead.
func (*DeleteIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteIntegrationResponse) Reset() {
	*x = DeleteIntegrationResponse{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIntegrationResponse) ProtoMessage() {}

func (x *DeleteIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIntegrationResponse.ProtoReflect.Descriptor instead.
func (*DeleteIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteIntegrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// Test integration
type TestIntegrationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIntegrationRequest) Reset() {
	*x = TestIntegrationRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIntegrationRequest) ProtoMessage() {}

func (x *TestIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIntegrationRequest.ProtoReflect.Descriptor instead.
func (*TestIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{9}
}

func (x *TestIntegrationRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TestIntegrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TestIntegrationResponse) Reset() {
	*x = TestIntegrationResponse{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TestIntegrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestIntegrationResponse) ProtoMessage() {}

func (x *TestIntegrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestIntegrationResponse.ProtoReflect.Descriptor instead.
func (*TestIntegrationResponse) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{10}
}

func (x *TestIntegrationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TestIntegrationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Get integration types
type GetIntegrationTypesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationTypesRequest) Reset() {
	*x = GetIntegrationTypesRequest{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationTypesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationTypesRequest) ProtoMessage() {}

func (x *GetIntegrationTypesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationTypesRequest.ProtoReflect.Descriptor instead.
func (*GetIntegrationTypesRequest) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{11}
}

type GetIntegrationTypesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Types         []*IntegrationTypeInfo `protobuf:"bytes,1,rep,name=types,proto3" json:"types,omitempty"`
	Events        []string               `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationTypesResponse) Reset() {
	*x = GetIntegrationTypesResponse{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationTypesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationTypesResponse) ProtoMessage() {}

func (x *GetIntegrationTypesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationTypesResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationTypesResponse) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{12}
}

func (x *GetIntegrationTypesResponse) GetTypes() []*IntegrationTypeInfo {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *GetIntegrationTypesResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

type IntegrationTypeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          IntegrationType        `protobuf:"varint,1,opt,name=type,proto3,enum=integrations.v1.IntegrationType" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Icon          string                 `protobuf:"bytes,4,opt,name=icon,proto3" json:"icon,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	ConfigFields  []*ConfigField         `protobuf:"bytes,6,rep,name=config_fields,json=configFields,proto3" json:"config_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IntegrationTypeInfo) Reset() {
	*x = IntegrationTypeInfo{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IntegrationTypeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IntegrationTypeInfo) ProtoMessage() {}

func (x *IntegrationTypeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IntegrationTypeInfo.ProtoReflect.Descriptor instead.
func (*IntegrationTypeInfo) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{13}
}

func (x *IntegrationTypeInfo) GetType() IntegrationType {
	if x != nil {
		return x.Type
	}
	return IntegrationType_INTEGRATION_TYPE_UNSPECIFIED
}

func (x *IntegrationTypeInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *IntegrationTypeInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *IntegrationTypeInfo) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *IntegrationTypeInfo) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *IntegrationTypeInfo) GetConfigFields() []*ConfigField {
	if x != nil {
		return x.ConfigFields
	}
	return nil
}

type ConfigField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Label         string                 `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	FieldType     string                 `protobuf:"bytes,3,opt,name=field_type,json=fieldType,proto3" json:"field_type,omitempty"`
	Required      bool                   `protobuf:"varint,4,opt,name=required,proto3" json:"required,omitempty"`
	Placeholder   string                 `protobuf:"bytes,5,opt,name=placeholder,proto3" json:"placeholder,omitempty"`
	HelpText      string                 `protobuf:"bytes,6,opt,name=help_text,json=helpText,proto3" json:"help_text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigField) Reset() {
	*x = ConfigField{}
	mi := &file_integrations_v1_integrations_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigField) ProtoMessage() {}

func (x *ConfigField) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_v1_integrations_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigField.ProtoReflect.Descriptor instead.
func (*ConfigField) Descriptor() ([]byte, []int) {
	return file_integrations_v1_integrations_proto_rawDescGZIP(), []int{14}
}

func (x *ConfigField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ConfigField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *ConfigField) GetFieldType() string {
	if x != nil {
		return x.FieldType
	}
	return ""
}

func (x *ConfigField) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ConfigField) GetPlaceholder() string {
	if x != nil {
		return x.Placeholder
	}
	return ""
}

func (x *ConfigField) GetHelpText() string {
	if x != nil {
		return x.HelpText
	}
	return ""
}

var File_integrations_v1_integrations_proto protoreflect.FileDescriptor

const file_integrations_v1_integrations_proto_rawDesc = "" +
	"\n" +
	"\"integrations/v1/integrations.proto\x12\x0fintegrations.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xef\x03\n" +
	"\vIntegration\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x124\n" +
	"\x04type\x18\x03 \x01(\x0e2 .integrations.v1.IntegrationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12:\n" +
	"\x06config\x18\x05 \x01(\v2\".integrations.v1.IntegrationConfigR\x06config\x12\x16\n" +
	"\x06events\x18\x06 \x03(\tR\x06events\x12\x1b\n" +
	"\tis_active\x18\a \x01(\bR\bisActive\x12K\n" +
	"\x11last_triggered_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0flastTriggeredAt\x88\x01\x01\x12#\n" +
	"\rtrigger_count\x18\t \x01(\x05R\ftriggerCount\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x14\n" +
	"\x12_last_triggered_at\"\xa1\x01\n" +
	"\x11IntegrationConfig\x12\x1f\n" +
	"\vwebhook_url\x18\x01 \x01(\tR\n" +
	"webhookUrl\x12\x18\n" +
	"\achannel\x18\x02 \x01(\tR\achannel\x12\x1b\n" +
	"\tbot_token\x18\x03 \x01(\tR\bbotToken\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\x12\x1b\n" +
	"\twrite_key\x18\x05 \x01(\tR\bwriteKey\"\x19\n" +
	"\x17ListIntegrationsRequest\"\\\n" +
	"\x18ListIntegrationsResponse\x12@\n" +
	"\fintegrations\x18\x01 \x03(\v2\x1c.integrations.v1.IntegrationR\fintegrations\"\xb8\x01\n" +
	"\x18CreateIntegrationRequest\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .integrations.v1.IntegrationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12:\n" +
	"\x06config\x18\x03 \x01(\v2\".integrations.v1.IntegrationConfigR\x06config\x12\x16\n" +
	"\x06events\x18\x04 \x03(\tR\x06events\"'\n" +
	"\x15GetIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe0\x01\n" +
	"\x18UpdateIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12?\n" +
	"\x06config\x18\x03 \x01(\v2\".integrations.v1.IntegrationConfigH\x01R\x06config\x88\x01\x01\x12\x16\n" +
	"\x06events\x18\x04 \x03(\tR\x06events\x12 \n" +
	"\tis_active\x18\x05 \x01(\bH\x02R\bisActive\x88\x01\x01B\a\n" +
	"\x05_nameB\t\n" +
	"\a_configB\f\n" +
	"\n" +
	"_is_active\"*\n" +
	"\x18DeleteIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x19DeleteIntegrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"(\n" +
	"\x16TestIntegrationRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"M\n" +
	"\x17TestIntegrationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x1c\n" +
	"\x1aGetIntegrationTypesRequest\"q\n" +
	"\x1bGetIntegrationTypesResponse\x12:\n" +
	"\x05types\x18\x01 \x03(\v2$.integrations.v1.IntegrationTypeInfoR\x05types\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\"\xf6\x01\n" +
	"\x13IntegrationTypeInfo\x124\n" +
	"\x04type\x18\x01 \x01(\x0e2 .integrations.v1.IntegrationTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x04 \x01(\tR\x04icon\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12A\n" +
	"\rconfig_fields\x18\x06 \x03(\v2\x1c.integrations.v1.ConfigFieldR\fconfigFields\"\xb1\x01\n" +
	"\vConfigField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x1d\n" +
	"\n" +
	"field_type\x18\x03 \x01(\tR\tfieldType\x12\x1a\n" +
	"\brequired\x18\x04 \x01(\bR\brequired\x12 \n" +
	"\vplaceholder\x18\x05 \x01(\tR\vplaceholder\x12\x1b\n" +
	"\thelp_text\x18\x06 \x01(\tR\bhelpText*\xc7\x01\n" +
	"\x0fIntegrationType\x12 \n" +
	"\x1cINTEGRATION_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INTEGRATION_TYPE_SLACK\x10\x01\x12\x1c\n" +
	"\x18INTEGRATION_TYPE_DISCORD\x10\x02\x12\x1d\n" +
	"\x19INTEGRATION_TYPE_TELEGRAM\x10\x03\x12\x1c\n" +
	"\x18INTEGRATION_TYPE_SEGMENT\x10\x04\x12\x1b\n" +
	"\x17INTEGRATION_TYPE_ZAPIER\x10\x052\xd5\x05\n" +
	"\x12IntegrationService\x12g\n" +
	"\x10ListIntegrations\x12(.integrations.v1.ListIntegrationsRequest\x1a).integrations.v1.ListIntegrationsResponse\x12\\\n" +
	"\x11CreateIntegration\x12).integrations.v1.CreateIntegrationRequest\x1a\x1c.integrations.v1.Integration\x12V\n" +
	"\x0eGetIntegration\x12&.integrations.v1.GetIntegrationRequest\x1a\x1c.integrations.v1.Integration\x12\\\n" +
	"\x11UpdateIntegration\x12).integrations.v1.UpdateIntegrationRequest\x1a\x1c.integrations.v1.Integration\x12j\n" +
	"\x11DeleteIntegration\x12).integrations.v1.DeleteIntegrationRequest\x1a*.integrations.v1.DeleteIntegrationResponse\x12d\n" +
	"\x0fTestIntegration\x12'.integrations.v1.TestIntegrationRequest\x1a(.integrations.v1.TestIntegrationResponse\x12p\n" +
	"\x13GetIntegrationTypes\x12+.integrations.v1.GetIntegrationTypesRequest\x1a,.integrations.v1.GetIntegrationTypesResponseBCZAgithub.com/go2-link/backend/pkg/pb/integrations/v1;integrationsv1b\x06proto3"

var (
	file_integrations_v1_integrations_proto_rawDescOnce sync.Once
	file_integrations_v1_integrations_proto_rawDescData []byte
)

func file_integrations_v1_integrations_proto_rawDescGZIP() []byte {
	file_integrations_v1_integrations_proto_rawDescOnce.Do(func() {
		file_integrations_v1_integrations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_integrations_v1_integrations_proto_rawDesc), len(file_integrations_v1_integrations_proto_rawDesc)))
	})
	return file_integrations_v1_integrations_proto_rawDescData
}

var file_integrations_v1_integrations_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_integrations_v1_integrations_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_integrations_v1_integrations_proto_goTypes = []any{
	(IntegrationType)(0),                // 0: integrations.v1.IntegrationType
	(*Integration)(nil),                 // 1: integrations.v1.Integration
	(*IntegrationConfig)(nil),           // 2: integrations.v1.IntegrationConfig
	(*ListIntegrationsRequest)(nil),     // 3: integrations.v1.ListIntegrationsRequest
	(*ListIntegrationsResponse)(nil),    // 4: integrations.v1.ListIntegrationsResponse
	(*CreateIntegrationRequest)(nil),    // 5: integrations.v1.CreateIntegrationRequest
	(*GetIntegrationRequest)(nil),       // 6: integrations.v1.GetIntegrationRequest
	(*UpdateIntegrationRequest)(nil),    // 7: integrations.v1.UpdateIntegrationRequest
	(*DeleteIntegrationRequest)(nil),    // 8: integrations.v1.DeleteIntegrationRequest
	(*DeleteIntegrationResponse)(nil),   // 9: integrations.v1.DeleteIntegrationResponse
	(*TestIntegrationRequest)(nil),      // 10: integrations.v1.TestIntegrationRequest
	(*TestIntegrationResponse)(nil),     // 11: integrations.v1.TestIntegrationResponse
	(*GetIntegrationTypesRequest)(nil),  // 12: integrations.v1.GetIntegrationTypesRequest
	(*GetIntegrationTypesResponse)(nil), // 13: integrations.v1.GetIntegrationTypesResponse
	(*IntegrationTypeInfo)(nil),         // 14: integrations.v1.IntegrationTypeInfo
	(*ConfigField)(nil),                 // 15: integrations.v1.ConfigField
	(*timestamppb.Timestamp)(nil),       // 16: google.protobuf.Timestamp
}
var file_integrations_v1_integrations_proto_depIdxs = []int32{
	0,  // 0: integrations.v1.Integration.type:type_name -> integrations.v1.IntegrationType
	2,  // 1: integrations.v1.Integration.config:type_name -> integrations.v1.IntegrationConfig
	16, // 2: integrations.v1.Integration.last_triggered_at:type_name -> google.protobuf.Timestamp
	16, // 3: integrations.v1.Integration.created_at:type_name -> google.protobuf.Timestamp
	16, // 4: integrations.v1.Integration.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 5: integrations.v1.ListIntegrationsResponse.integrations:type_name -> integrations.v1.Integration
	0,  // 6: integrations.v1.CreateIntegrationRequest.type:type_name -> integrations.v1.IntegrationType
	2,  // 7: integrations.v1.CreateIntegrationRequest.config:type_name -> integrations.v1.IntegrationConfig
	2,  // 8: integrations.v1.UpdateIntegrationRequest.config:type_name -> integrations.v1.IntegrationConfig
	14, // 9: integrations.v1.GetIntegrationTypesResponse.types:type_name -> integrations.v1.IntegrationTypeInfo
	0,  // 10: integrations.v1.IntegrationTypeInfo.type:type_name -> integrations.v1.IntegrationType
	15, // 11: integrations.v1.IntegrationTypeInfo.config_fields:type_name -> integrations.v1.ConfigField
	3,  // 12: integrations.v1.IntegrationService.ListIntegrations:input_type -> integrations.v1.ListIntegrationsRequest
	5,  // 13: integrations.v1.IntegrationService.CreateIntegration:input_type -> integrations.v1.CreateIntegrationRequest
	6,  // 14: integrations.v1.IntegrationService.GetIntegration:input_type -> integrations.v1.GetIntegrationRequest
	7,  // 15: integrations.v1.IntegrationService.UpdateIntegration:input_type -> integrations.v1.UpdateIntegrationRequest
	8,  // 16: integrations.v1.IntegrationService.DeleteIntegration:input_type -> integrations.v1.DeleteIntegrationRequest
	10, // 17: integrations.v1.IntegrationService.TestIntegration:input_type -> integrations.v1.TestIntegrationRequest
	12, // 18: integrations.v1.IntegrationService.GetIntegrationTypes:input_type -> integrations.v1.GetIntegrationTypesRequest
	4,  // 19: integrations.v1.IntegrationService.ListIntegrations:output_type -> integrations.v1.ListIntegrationsResponse
	1,  // 20: integrations.v1.IntegrationService.CreateIntegration:output_type -> integrations.v1.Integration
	1,  // 21: integrations.v1.IntegrationService.GetIntegration:output_type -> integrations.v1.Integration
	1,  // 22: integrations.v1.IntegrationService.UpdateIntegration:output_type -> integrations.v1.Integration
	9,  // 23: integrations.v1.IntegrationService.DeleteIntegration:output_type -> integrations.v1.DeleteIntegrationResponse
	11, // 24: integrations.v1.IntegrationService.TestIntegration:output_type -> integrations.v1.TestIntegrationResponse
	13, // 25: integrations.v1.IntegrationService.GetIntegrationTypes:output_type -> integrations.v1.GetIntegrationTypesResponse
	19, // [19:26] is the sub-list for method output_type
	12, // [12:19] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_integrations_v1_integrations_proto_init() }
func file_integrations_v1_integrations_proto_init() {
	if File_integrations_v1_integrations_proto != nil {
		return
	}
	file_integrations_v1_integrations_proto_msgTypes[0].OneofWrappers = []any{}
	file_integrations_v1_integrations_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_integrations_v1_integrations_proto_rawDesc), len(file_integrations_v1_integrations_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integrations_v1_integrations_proto_goTypes,
		DependencyIndexes: file_integrations_v1_integrations_proto_depIdxs,
		EnumInfos:         file_integrations_v1_integrations_proto_enumTypes,
		MessageInfos:      file_integrations_v1_integrations_proto_msgTypes,
	}.Build()
	File_integrations_v1_integrations_proto = out.File
	file_integrations_v1_integrations_proto_goTypes = nil
	file_integrations_v1_integrations_proto_depIdxs = nil
}
