// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: domains/v1/domains.proto

package domainsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Domain status
type DomainStatus int32

const (
	DomainStatus_DOMAIN_STATUS_UNSPECIFIED DomainStatus = 0
	DomainStatus_DOMAIN_STATUS_PENDING     DomainStatus = 1
	DomainStatus_DOMAIN_STATUS_VERIFYING   DomainStatus = 2
	DomainStatus_DOMAIN_STATUS_ACTIVE      DomainStatus = 3
	DomainStatus_DOMAIN_STATUS_FAILED      DomainStatus = 4
)

// Enum value maps for DomainStatus.
var (
	DomainStatus_name = map[int32]string{
		0: "DOMAIN_STATUS_UNSPECIFIED",
		1: "DOMAIN_STATUS_PENDING",
		2: "DOMAIN_STATUS_VERIFYING",
		3: "DOMAIN_STATUS_ACTIVE",
		4: "DOMAIN_STATUS_FAILED",
	}
	DomainStatus_value = map[string]int32{
		"DOMAIN_STATUS_UNSPECIFIED": 0,
		"DOMAIN_STATUS_PENDING":     1,
		"DOMAIN_STATUS_VERIFYING":   2,
		"DOMAIN_STATUS_ACTIVE":      3,
		"DOMAIN_STATUS_FAILED":      4,
	}
)

func (x DomainStatus) Enum() *DomainStatus {
	p := new(DomainStatus)
	*p = x
	return p
}

func (x DomainStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DomainStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domains_v1_domains_proto_enumTypes[0].Descriptor()
}

func (DomainStatus) Type() protoreflect.EnumType {
	return &file_domains_v1_domains_proto_enumTypes[0]
}

func (x DomainStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DomainStatus.Descriptor instead.
func (DomainStatus) EnumDescriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{0}
}

// SSL status
type SSLStatus int32

const (
	SSLStatus_SSL_STATUS_UNSPECIFIED  SSLStatus = 0
	SSLStatus_SSL_STATUS_PENDING      SSLStatus = 1
	SSLStatus_SSL_STATUS_PROVISIONING SSLStatus = 2
	SSLStatus_SSL_STATUS_ACTIVE       SSLStatus = 3
	SSLStatus_SSL_STATUS_FAILED       SSLStatus = 4
)

// Enum value maps for SSLStatus.
var (
	SSLStatus_name = map[int32]string{
		0: "SSL_STATUS_UNSPECIFIED",
		1: "SSL_STATUS_PENDING",
		2: "SSL_STATUS_PROVISIONING",
		3: "SSL_STATUS_ACTIVE",
		4: "SSL_STATUS_FAILED",
	}
	SSLStatus_value = map[string]int32{
		"SSL_STATUS_UNSPECIFIED":  0,
		"SSL_STATUS_PENDING":      1,
		"SSL_STATUS_PROVISIONING": 2,
		"SSL_STATUS_ACTIVE":       3,
		"SSL_STATUS_FAILED":       4,
	}
)

func (x SSLStatus) Enum() *SSLStatus {
	p := new(SSLStatus)
	*p = x
	return p
}

func (x SSLStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SSLStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_domains_v1_domains_proto_enumTypes[1].Descriptor()
}

func (SSLStatus) Type() protoreflect.EnumType {
	return &file_domains_v1_domains_proto_enumTypes[1]
}

func (x SSLStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SSLStatus.Descriptor instead.
func (SSLStatus) EnumDescriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{1}
}

// Domain represents a custom domain
type Domain struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId               string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Domain               string                 `protobuf:"bytes,3,opt,name=domain,proto3" json:"domain,omitempty"`
	Status               DomainStatus           `protobuf:"varint,4,opt,name=status,proto3,enum=domains.v1.DomainStatus" json:"status,omitempty"`
	VerificationToken    string                 `protobuf:"bytes,5,opt,name=verification_token,json=verificationToken,proto3" json:"verification_token,omitempty"`
	VerifiedAt           *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=verified_at,json=verifiedAt,proto3,oneof" json:"verified_at,omitempty"`
	SslStatus            SSLStatus              `protobuf:"varint,7,opt,name=ssl_status,json=sslStatus,proto3,enum=domains.v1.SSLStatus" json:"ssl_status,omitempty"`
	CloudflareHostnameId string                 `protobuf:"bytes,8,opt,name=cloudflare_hostname_id,json=cloudflareHostnameId,proto3" json:"cloudflare_hostname_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Domain) Reset() {
	*x = Domain{}
	mi := &file_domains_v1_domains_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Domain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Domain) ProtoMessage() {}

func (x *Domain) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Domain.ProtoReflect.Descriptor instead.
func (*Domain) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{0}
}

func (x *Domain) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Domain) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Domain) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *Domain) GetStatus() DomainStatus {
	if x != nil {
		return x.Status
	}
	return DomainStatus_DOMAIN_STATUS_UNSPECIFIED
}

func (x *Domain) GetVerificationToken() string {
	if x != nil {
		return x.VerificationToken
	}
	return ""
}

func (x *Domain) GetVerifiedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.VerifiedAt
	}
	return nil
}

func (x *Domain) GetSslStatus() SSLStatus {
	if x != nil {
		return x.SslStatus
	}
	return SSLStatus_SSL_STATUS_UNSPECIFIED
}

func (x *Domain) GetCloudflareHostnameId() string {
	if x != nil {
		return x.CloudflareHostnameId
	}
	return ""
}

func (x *Domain) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Domain) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// DNS record for domain setup
type DNSRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DNSRecord) Reset() {
	*x = DNSRecord{}
	mi := &file_domains_v1_domains_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DNSRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DNSRecord) ProtoMessage() {}

func (x *DNSRecord) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DNSRecord.ProtoReflect.Descriptor instead.
func (*DNSRecord) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{1}
}

func (x *DNSRecord) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DNSRecord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DNSRecord) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// List domains
type ListDomainsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsRequest) Reset() {
	*x = ListDomainsRequest{}
	mi := &file_domains_v1_domains_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsRequest) ProtoMessage() {}

func (x *ListDomainsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsRequest.ProtoReflect.Descriptor instead.
func (*ListDomainsRequest) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{2}
}

type ListDomainsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domains       []*Domain              `protobuf:"bytes,1,rep,name=domains,proto3" json:"domains,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDomainsResponse) Reset() {
	*x = ListDomainsResponse{}
	mi := &file_domains_v1_domains_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDomainsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDomainsResponse) ProtoMessage() {}

func (x *ListDomainsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDomainsResponse.ProtoReflect.Descriptor instead.
func (*ListDomainsResponse) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{3}
}

func (x *ListDomainsResponse) GetDomains() []*Domain {
	if x != nil {
		return x.Domains
	}
	return nil
}

// Create domain
type CreateDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        string                 `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDomainRequest) Reset() {
	*x = CreateDomainRequest{}
	mi := &file_domains_v1_domains_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainRequest) ProtoMessage() {}

func (x *CreateDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainRequest.ProtoReflect.Descriptor instead.
func (*CreateDomainRequest) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{4}
}

func (x *CreateDomainRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

type CreateDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Domain        *Domain                `protobuf:"bytes,1,opt,name=domain,proto3" json:"domain,omitempty"`
	DnsRecords    []*DNSRecord           `protobuf:"bytes,2,rep,name=dns_records,json=dnsRecords,proto3" json:"dns_records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDomainResponse) Reset() {
	*x = CreateDomainResponse{}
	mi := &file_domains_v1_domains_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDomainResponse) ProtoMessage() {}

func (x *CreateDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDomainResponse.ProtoReflect.Descriptor instead.
func (*CreateDomainResponse) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{5}
}

func (x *CreateDomainResponse) GetDomain() *Domain {
	if x != nil {
		return x.Domain
	}
	return nil
}

func (x *CreateDomainResponse) GetDnsRecords() []*DNSRecord {
	if x != nil {
		return x.DnsRecords
	}
	return nil
}

// Get domain
type GetDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDomainRequest) Reset() {
	*x = GetDomainRequest{}
	mi := &file_domains_v1_domains_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDomainRequest) ProtoMessage() {}

func (x *GetDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDomainRequest.ProtoReflect.Descriptor instead.
func (*GetDomainRequest) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{6}
}

func (x *GetDomainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Verify domain
type VerifyDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyDomainRequest) Reset() {
	*x = VerifyDomainRequest{}
	mi := &file_domains_v1_domains_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyDomainRequest) ProtoMessage() {}

func (x *VerifyDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyDomainRequest.ProtoReflect.Descriptor instead.
func (*VerifyDomainRequest) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{7}
}

func (x *VerifyDomainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Delete domain
type DeleteDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainRequest) Reset() {
	*x = DeleteDomainRequest{}
	mi := &file_domains_v1_domains_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainRequest) ProtoMessage() {}

func (x *DeleteDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainRequest.ProtoReflect.Descriptor instead.
func (*DeleteDomainRequest) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteDomainRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDomainResponse) Reset() {
	*x = DeleteDomainResponse{}
	mi := &file_domains_v1_domains_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDomainResponse) ProtoMessage() {}

func (x *DeleteDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_domains_v1_domains_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDomainResponse.ProtoReflect.Descriptor instead.
func (*DeleteDomainResponse) Descriptor() ([]byte, []int) {
	return file_domains_v1_domains_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDomainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteDomainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_domains_v1_domains_proto protoreflect.FileDescriptor

const file_domains_v1_domains_proto_rawDesc = "" +
	"\n" +
	"\x18domains/v1/domains.proto\x12\n" +
	"domains.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xde\x03\n" +
	"\x06Domain\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06domain\x18\x03 \x01(\tR\x06domain\x120\n" +
	"\x06status\x18\x04 \x01(\x0e2\x18.domains.v1.DomainStatusR\x06status\x12-\n" +
	"\x12verification_token\x18\x05 \x01(\tR\x11verificationToken\x12@\n" +
	"\vverified_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\n" +
	"verifiedAt\x88\x01\x01\x124\n" +
	"\n" +
	"ssl_status\x18\a \x01(\x0e2\x15.domains.v1.SSLStatusR\tsslStatus\x124\n" +
	"\x16cloudflare_hostname_id\x18\b \x01(\tR\x14cloudflareHostnameId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\x0e\n" +
	"\f_verified_at\"I\n" +
	"\tDNSRecord\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"\x14\n" +
	"\x12ListDomainsRequest\"C\n" +
	"\x13ListDomainsResponse\x12,\n" +
	"\adomains\x18\x01 \x03(\v2\x12.domains.v1.DomainR\adomains\"-\n" +
	"\x13CreateDomainRequest\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\"z\n" +
	"\x14CreateDomainResponse\x12*\n" +
	"\x06domain\x18\x01 \x01(\v2\x12.domains.v1.DomainR\x06domain\x126\n" +
	"\vdns_records\x18\x02 \x03(\v2\x15.domains.v1.DNSRecordR\n" +
	"dnsRecords\"\"\n" +
	"\x10GetDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13VerifyDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13DeleteDomainRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"J\n" +
	"\x14DeleteDomainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x99\x01\n" +
	"\fDomainStatus\x12\x1d\n" +
	"\x19DOMAIN_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DOMAIN_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17DOMAIN_STATUS_VERIFYING\x10\x02\x12\x18\n" +
	"\x14DOMAIN_STATUS_ACTIVE\x10\x03\x12\x18\n" +
	"\x14DOMAIN_STATUS_FAILED\x10\x04*\x8a\x01\n" +
	"\tSSLStatus\x12\x1a\n" +
	"\x16SSL_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SSL_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17SSL_STATUS_PROVISIONING\x10\x02\x12\x15\n" +
	"\x11SSL_STATUS_ACTIVE\x10\x03\x12\x15\n" +
	"\x11SSL_STATUS_FAILED\x10\x042\x89\x03\n" +
	"\rDomainService\x12N\n" +
	"\vListDomains\x12\x1e.domains.v1.ListDomainsRequest\x1a\x1f.domains.v1.ListDomainsResponse\x12Q\n" +
	"\fCreateDomain\x12\x1f.domains.v1.CreateDomainRequest\x1a .domains.v1.CreateDomainResponse\x12=\n" +
	"\tGetDomain\x12\x1c.domains.v1.GetDomainRequest\x1a\x12.domains.v1.Domain\x12C\n" +
	"\fVerifyDomain\x12\x1f.domains.v1.VerifyDomainRequest\x1a\x12.domains.v1.Domain\x12Q\n" +
	"\fDeleteDomain\x12\x1f.domains.v1.DeleteDomainRequest\x1a .domains.v1.DeleteDomainResponseB5Z3github.com/gosms-ge/go2-sdk/go/domains/v1;domainsv1b\x06proto3"

var (
	file_domains_v1_domains_proto_rawDescOnce sync.Once
	file_domains_v1_domains_proto_rawDescData []byte
)

func file_domains_v1_domains_proto_rawDescGZIP() []byte {
	file_domains_v1_domains_proto_rawDescOnce.Do(func() {
		file_domains_v1_domains_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_domains_v1_domains_proto_rawDesc), len(file_domains_v1_domains_proto_rawDesc)))
	})
	return file_domains_v1_domains_proto_rawDescData
}

var file_domains_v1_domains_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_domains_v1_domains_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_domains_v1_domains_proto_goTypes = []any{
	(DomainStatus)(0),             // 0: domains.v1.DomainStatus
	(SSLStatus)(0),                // 1: domains.v1.SSLStatus
	(*Domain)(nil),                // 2: domains.v1.Domain
	(*DNSRecord)(nil),             // 3: domains.v1.DNSRecord
	(*ListDomainsRequest)(nil),    // 4: domains.v1.ListDomainsRequest
	(*ListDomainsResponse)(nil),   // 5: domains.v1.ListDomainsResponse
	(*CreateDomainRequest)(nil),   // 6: domains.v1.CreateDomainRequest
	(*CreateDomainResponse)(nil),  // 7: domains.v1.CreateDomainResponse
	(*GetDomainRequest)(nil),      // 8: domains.v1.GetDomainRequest
	(*VerifyDomainRequest)(nil),   // 9: domains.v1.VerifyDomainRequest
	(*DeleteDomainRequest)(nil),   // 10: domains.v1.DeleteDomainRequest
	(*DeleteDomainResponse)(nil),  // 11: domains.v1.DeleteDomainResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
}
var file_domains_v1_domains_proto_depIdxs = []int32{
	0,  // 0: domains.v1.Domain.status:type_name -> domains.v1.DomainStatus
	12, // 1: domains.v1.Domain.verified_at:type_name -> google.protobuf.Timestamp
	1,  // 2: domains.v1.Domain.ssl_status:type_name -> domains.v1.SSLStatus
	12, // 3: domains.v1.Domain.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: domains.v1.Domain.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 5: domains.v1.ListDomainsResponse.domains:type_name -> domains.v1.Domain
	2,  // 6: domains.v1.CreateDomainResponse.domain:type_name -> domains.v1.Domain
	3,  // 7: domains.v1.CreateDomainResponse.dns_records:type_name -> domains.v1.DNSRecord
	4,  // 8: domains.v1.DomainService.ListDomains:input_type -> domains.v1.ListDomainsRequest
	6,  // 9: domains.v1.DomainService.CreateDomain:input_type -> domains.v1.CreateDomainRequest
	8,  // 10: domains.v1.DomainService.GetDomain:input_type -> domains.v1.GetDomainRequest
	9,  // 11: domains.v1.DomainService.VerifyDomain:input_type -> domains.v1.VerifyDomainRequest
	10, // 12: domains.v1.DomainService.DeleteDomain:input_type -> domains.v1.DeleteDomainRequest
	5,  // 13: domains.v1.DomainService.ListDomains:output_type -> domains.v1.ListDomainsResponse
	7,  // 14: domains.v1.DomainService.CreateDomain:output_type -> domains.v1.CreateDomainResponse
	2,  // 15: domains.v1.DomainService.GetDomain:output_type -> domains.v1.Domain
	2,  // 16: domains.v1.DomainService.VerifyDomain:output_type -> domains.v1.Domain
	11, // 17: domains.v1.DomainService.DeleteDomain:output_type -> domains.v1.DeleteDomainResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_domains_v1_domains_proto_init() }
func file_domains_v1_domains_proto_init() {
	if File_domains_v1_domains_proto != nil {
		return
	}
	file_domains_v1_domains_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_domains_v1_domains_proto_rawDesc), len(file_domains_v1_domains_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_domains_v1_domains_proto_goTypes,
		DependencyIndexes: file_domains_v1_domains_proto_depIdxs,
		EnumInfos:         file_domains_v1_domains_proto_enumTypes,
		MessageInfos:      file_domains_v1_domains_proto_msgTypes,
	}.Build()
	File_domains_v1_domains_proto = out.File
	file_domains_v1_domains_proto_goTypes = nil
	file_domains_v1_domains_proto_depIdxs = nil
}
