// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: qr/v1/qr.proto

package qrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Generate QR
type GenerateQRRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LinkId          string                 `protobuf:"bytes,1,opt,name=link_id,json=linkId,proto3" json:"link_id,omitempty"`
	Size            int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`                                             // 128, 256, 512, 1024
	Format          string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`                                          // png, svg
	ForegroundColor string                 `protobuf:"bytes,4,opt,name=foreground_color,json=foregroundColor,proto3" json:"foreground_color,omitempty"` // hex color
	BackgroundColor string                 `protobuf:"bytes,5,opt,name=background_color,json=backgroundColor,proto3" json:"background_color,omitempty"` // hex color
	LogoUrl         string                 `protobuf:"bytes,6,opt,name=logo_url,json=logoUrl,proto3" json:"logo_url,omitempty"`                         // optional logo overlay
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GenerateQRRequest) Reset() {
	*x = GenerateQRRequest{}
	mi := &file_qr_v1_qr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRRequest) ProtoMessage() {}

func (x *GenerateQRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_qr_v1_qr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRRequest.ProtoReflect.Descriptor instead.
func (*GenerateQRRequest) Descriptor() ([]byte, []int) {
	return file_qr_v1_qr_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateQRRequest) GetLinkId() string {
	if x != nil {
		return x.LinkId
	}
	return ""
}

func (x *GenerateQRRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateQRRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *GenerateQRRequest) GetForegroundColor() string {
	if x != nil {
		return x.ForegroundColor
	}
	return ""
}

func (x *GenerateQRRequest) GetBackgroundColor() string {
	if x != nil {
		return x.BackgroundColor
	}
	return ""
}

func (x *GenerateQRRequest) GetLogoUrl() string {
	if x != nil {
		return x.LogoUrl
	}
	return ""
}

type GenerateQRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Format        string                 `protobuf:"bytes,3,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateQRResponse) Reset() {
	*x = GenerateQRResponse{}
	mi := &file_qr_v1_qr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateQRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateQRResponse) ProtoMessage() {}

func (x *GenerateQRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_qr_v1_qr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateQRResponse.ProtoReflect.Descriptor instead.
func (*GenerateQRResponse) Descriptor() ([]byte, []int) {
	return file_qr_v1_qr_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateQRResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GenerateQRResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GenerateQRResponse) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var File_qr_v1_qr_proto protoreflect.FileDescriptor

const file_qr_v1_qr_proto_rawDesc = "" +
	"\n" +
	"\x0eqr/v1/qr.proto\x12\x05qr.v1\"\xc9\x01\n" +
	"\x11GenerateQRRequest\x12\x17\n" +
	"\alink_id\x18\x01 \x01(\tR\x06linkId\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format\x12)\n" +
	"\x10foreground_color\x18\x04 \x01(\tR\x0fforegroundColor\x12)\n" +
	"\x10background_color\x18\x05 \x01(\tR\x0fbackgroundColor\x12\x19\n" +
	"\blogo_url\x18\x06 \x01(\tR\alogoUrl\"R\n" +
	"\x12GenerateQRResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x16\n" +
	"\x06format\x18\x03 \x01(\tR\x06format2N\n" +
	"\tQRService\x12A\n" +
	"\n" +
	"GenerateQR\x12\x18.qr.v1.GenerateQRRequest\x1a\x19.qr.v1.GenerateQRResponseB+Z)github.com/gosms-ge/go2-sdk/go/qr/v1;qrv1b\x06proto3"

var (
	file_qr_v1_qr_proto_rawDescOnce sync.Once
	file_qr_v1_qr_proto_rawDescData []byte
)

func file_qr_v1_qr_proto_rawDescGZIP() []byte {
	file_qr_v1_qr_proto_rawDescOnce.Do(func() {
		file_qr_v1_qr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_qr_v1_qr_proto_rawDesc), len(file_qr_v1_qr_proto_rawDesc)))
	})
	return file_qr_v1_qr_proto_rawDescData
}

var file_qr_v1_qr_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_qr_v1_qr_proto_goTypes = []any{
	(*GenerateQRRequest)(nil),  // 0: qr.v1.GenerateQRRequest
	(*GenerateQRResponse)(nil), // 1: qr.v1.GenerateQRResponse
}
var file_qr_v1_qr_proto_depIdxs = []int32{
	0, // 0: qr.v1.QRService.GenerateQR:input_type -> qr.v1.GenerateQRRequest
	1, // 1: qr.v1.QRService.GenerateQR:output_type -> qr.v1.GenerateQRResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_qr_v1_qr_proto_init() }
func file_qr_v1_qr_proto_init() {
	if File_qr_v1_qr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_qr_v1_qr_proto_rawDesc), len(file_qr_v1_qr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_qr_v1_qr_proto_goTypes,
		DependencyIndexes: file_qr_v1_qr_proto_depIdxs,
		MessageInfos:      file_qr_v1_qr_proto_msgTypes,
	}.Build()
	File_qr_v1_qr_proto = out.File
	file_qr_v1_qr_proto_goTypes = nil
	file_qr_v1_qr_proto_depIdxs = nil
}
